### ISSUE TITLE
Choose Your Audience & Schedule should not be green until initial distribution time is set

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#10]
(item from backlog)

**Comment by daver78** [comment]
@paagla123 I assume you agree and that this makes sense from user perspective?

**Comment by paweenwich** [comment]
@daver78 Agree

**Comment by daver78** [comment]
@paweenwich and @paagla123 OK let's proceed with this style and see if it feels right for the User.

**Comment by paweenwich** [comment]
Implemented, please take a look.

**Comment by paagla123** [comment]
Yes. All I said is that "Configure Notification etc" should turn green as soon as "Choose Audience and Schedule" turns green.

**Comment by paagla123** [comment]
We ready to close this now?

**Comment by daver78** [comment]
@paagla123 Can you confirm you took a look per @paweenwich "implemented" comment above?  Once you've verified, we can close.

**Comment by paagla123** [comment]
@daver78 OK.

**Comment by paagla123** [comment]
Working fine. Closed!
