### ISSUE TITLE
Add a way to upload a logo for Company Email template in the Blog Post Email

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#100]
@daver78 @paweenwich  - use Summernote here again?

**Comment by jiewsone** [comment]
Which page is you decide to upload logo image? Images in Asset Library?

![capture2](https://user-images.githubusercontent.com/30495168/30473104-5065c46a-9a29-11e7-8a18-a7c87b310977.JPG)

**Comment by daver78** [comment]
This is same as #54

**Comment by paagla123** [comment]
@daver78 neither - setup page

**Comment by jiewsone** [comment]
I already add "Company Logo" in Setting page.
But after you upload image, the image preview not change because we replace the old file.
You have to reload page by press ctrl+f5, it will show the correct image.
I will fix it tomorrow.

**Comment by jiewsone** [comment]
I already fix it.

**Comment by paagla123** [comment]
Done in Staging
