### ISSUE TITLE
Audience List not sorted correctly - it should be sorted by most recently edited first

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#101]

**Comment by paagla123** [comment]
@AumpaiFung have you had a chance to look at it?

**Comment by paweenwich** [comment]
I think we should hold this until we solve the sort problem in my campaign.   If we can not sort my campaign correctly, this one will has the same bug.

**Comment by paagla123** [comment]
@paweenwich I don't think they are same issue, but we can wait

**Comment by paagla123** [comment]
@AumpaiFung this is not fixed yet

**Comment by paweenwich** [comment]
Fung finish this one,  on stage.

**Comment by paagla123** [comment]
@AumpaiFung most recently updated going to the end

**Comment by AumpaiFung** [comment]
@paagla123
Audience still not sorting. I'm working on it.

**Comment by AumpaiFung** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
@AumpaiFung pl show me tonight - I am still havig issues.

**Comment by paagla123** [comment]
Fixed in Stage now

**Comment by paagla123** [comment]
@AumpaiFung @paweenwich @coa0329 this is fixed in Staging. How come it does not work in production? I thought you all said production and staging code are same now. Pl advise ASAP. Thx
