### ISSUE TITLE
[Promote a Blog Post] angular-chosen form field width issue

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#102]
For some reason, `angular-chosen` form field widths are not obeying my commands.  It sometimes looks like the below. [Here's documentation](https://github.com/leocaseiro/angular-chosen).

Since at the show everyone's monitor is big enough and if necessary I can tell them to hit CNTRL-MINUS to get things in view, we should be OK.  However, needs research to fix.

![image](https://user-images.githubusercontent.com/7561473/30228927-b0617b6a-9494-11e7-8035-aaaeb216d2a0.png)

@paagla123 thanks for reminding me about this.

**Comment by daver78** [comment]
@paweenwich If there is time next week, perhaps you can assign someone to this?  If not I will get back to it in about 7 days.

**Comment by paweenwich** [comment]
I fixed this one. please check the PromoteBlog first email on stage.

Basically, 
chosen always set with = 100%.  So, need to put it in other container in order to set width.

**Comment by daver78** [comment]
@paweenwich Make sense.  Perfect; thank you!

**Comment by paagla123** [comment]
Fixed in stage thank you @paweenwich

**Comment by paagla123** [comment]
@paweenwich this still has problems in smaller screens. Seems to be fixed in Staging. Pl confirm.

**Comment by daver78** [comment]
@paagla123 I think you're talking about a related but different issue.  Can you put a snapshot of what you are seeing?
