### ISSUE TITLE
[Audiences] May need a way to set a filter row that is used by every Audience, even if User doesn't explicitly set it

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#106]
For example, within MindFire, we use `sf_hasOptedOut` to mark opt-outs.  A problem we often has if people forget to include this row in their TA.

In DV, the same thing could happen, but I think we should think about some way to control this at the account level.

There could be other fields too.  This is just a placeholder for the thought so I don't forget.

**Comment by paagla123** [comment]
@daver78 I don't get it - why do you say so? However, we should note that we need to have a way to address all contacts. Currently we do not have any audience for all contacts.

**Comment by daver78** [comment]
@paagla123 Let me know if you mean "I don't agree with this requirement" or you mean "I don't understand the requirement."

Regarding a way to target all Contacts, should there be a default Segment called "All My Contacts"?  Or is that too dangerous?

**Comment by paagla123** [comment]
@daver78 I see - understand now. Thx

**Comment by paagla123** [comment]
@daver78 opt-outs in Studio are automatic - why do we need to mark a row? We're not using any custom unsubscribe here - right? I am still confused about this issue.

**Comment by daver78** [comment]
@paagla123 So when you said "I see - understand now" what was that about?  Was that the default segment called "All Contacts"?  I think you raise a good point on that issue, and we should figure out how to address elegantly.

-----

Regarding "opt-outs in Studio are automatic", that may be true in some cases, but certainly not all.  For example, when you run @Mcfarsheed's campaign(s) related to #108, you'll find that there are at least one row that all Segments require to handle the custom opt-out.  

I have no problem if you do it manually via the Segment filter for right now, but my gut tells me we will find this to be a recurring need.

The other time I see it coming into play is use cases where contacts belong to certain people, like sales reps.  

For example, let's imagine that we give Joe and Mary access to DV to nurture their own leads and Opps.  I would not want ANY chance of Joe accidentally sending to Mary's contacts.  Right?

That means that when we set up Joe's user in DV, there should be a place where we (the admin user at MindFire) can designate that his Segment filter should always contain something like `leadOwner = Joe Manos` or `contactOwner = Joe Manos `

Ya feel me, babe?

We definitely want sales people to log in and run their own sh*t.  But we also don't want sales people to cause more sh*t for people like you and @Mcfarsheed :)

**Comment by paagla123** [comment]
@daver78 do we want to worry about non-standard unsubscribes in the initial incarnation of daVinci? Normal people will not think about it. Its too complex a concept for them

**Comment by daver78** [comment]
@paagla123 I have no problem if you do it manually via the Segment filter for right now, but my gut tells me we will find this to be a recurring need (in the future).  Let's agree to wait and see what happens?

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#54
