### ISSUE TITLE
Form Copy Feature does not work

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#107]

**Comment by AumpaiFung** [comment]
I think you mean Asset Library.
Now Audiences have not Copy button.

**Comment by paweenwich** [comment]
Fung did the form copy.  please check on stage.

**Comment by paagla123** [comment]
@AumpaiFung works in stage thank you. Should we not have a different name, e.g. Copy of XXXX as the new form name?

**Comment by AumpaiFung** [comment]
@paagla123 
Done.

**Comment by paagla123** [comment]
@AumpaiFung thank you
