### ISSUE TITLE
Prepare assets for Kushal to run a "real" 'Promote a Blog Post' campaign.

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#108]
@Mcfarsheed, as discussed, I want you to have Kushal run one of your "Tuesday" content promotions.  He'll use the Blueprint to run it and thru that process, discover additional areas of polish that are required.

If he feels he needs another Campaign or two to continue improving things, we'll open up another issue.

If not, we'll then ask you to run a Campaign and provide @paagla123 with feedback.

Basically, here's what @paagla123 needs from you:

- URL to a blog post you want to promote
- The UTM string you want to use
- The email content you want to use, including hero image at top
- When you want emails 2 and 3 to hit 

I think that's it, but @paagla123 can add to this if there are other things he needs.

**Comment by paagla123** [comment]
@daver78 we need to get the MindFire logo back...
If thi sis for real we need to add daVinci to MindFire Master

**Comment by daver78** [comment]
@paagla123 I think you created an issue for allowing the User to upload their company logo.  Should resolve this, yes?

**Comment by paagla123** [comment]
@Mcfarsheed what's the plan here?

**Comment by paagla123** [comment]
@Mcfarsheed let's chat tomorrow

**Comment by Mcfarsheed** [comment]
ok! I'll call you!

Sincerely,

Mackenzi
MindFireInc.
949-842-4388
www.mindfireinc.com

**Comment by paagla123** [comment]
For you @Mcfarsheed 
https://youtu.be/-mVMvfqnUWs?t=45s

**Comment by Mcfarsheed** [comment]
haha Kush!

Sincerely,

Mackenzi
MindFireInc.
949-842-4388
www.mindfireinc.com

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#100
