### ISSUE TITLE
Remove all references to any assets located on Dave's C9 environment

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#109]
I though we handled this, but I still see that teh old man's picture on teh top left pf the screen points to https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/DV-CMS-UI/DV-logo.png . This should be hosted in S3. Likewise, if there are any others like this, it needs to be moved to S3.

**Comment by paweenwich** [comment]
Done
