### ISSUE TITLE
Sync UI with Dave's daVinci

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#11]
(item from backlog)
- update style.css
- Regarding https://web2xmm.com/admin/welcome.php: Favicon, DV'simage, table at bottom, jumbotron at top —- are all different than mockup.
- We’re missing the “chosen” plugin for form fields.  (like editing your email)
- Wrapper is still old. 
- Regarding https://web2xmm.com/admin/login.html:  (using Dave provided login page)

**Comment by paagla123** [comment]
@paweenwich should we close this after @jiewsone is done with the eBook?

**Comment by daver78** [comment]
@paagla123 I don't think so.  There are still a # of inconsistencies.  Who is going to make a list, or do we not need to?

**Comment by paweenwich** [comment]
@daver78 Fung did apply your style.css.  If things are still not correct, could you please make a list of the # of inconsistencies (order by the importance).  So, we have something to working on this issue.

**Comment by daver78** [comment]
@paweenwich Yes, I/we can do that.  When do you want the list?

@paagla123 You may be able to help with this?

**Comment by daver78** [comment]
@paagla123 and @paweenwich We will close this.  Either I or @paagla123 will create specific issues that the team should work on, if required.
