### ISSUE TITLE
View / browse contacts should open in a different tab

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#110]
When we click on view all my contacts or click on a contact list, the list of contacts should open in a different tab.

**Comment by paweenwich** [comment]
Done

**Comment by daver78** [comment]
@paagla123 This area needs major love.  Once you've tested this, can you create a new Issue for the Love?

**Comment by paagla123** [comment]
@paweenwich this is fixed for See All My Contacts. Needs same behavior when we select one of the audiences

**Comment by paweenwich** [comment]
@paagla123 
![capture](https://user-images.githubusercontent.com/17819797/30527004-deab3bbc-9c4d-11e7-88a4-50a923af92a2.PNG)

I am not where you are talking about.  It open the new tab when I click around the blue circle area.

**Comment by coa0329** [comment]
Fixed.
