### ISSUE TITLE
Which branch should I pull?

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#112]
@paweenwich I saw that there are 9 branches in BhaangWeb.  Which one should I pull and push to in order to contribute?

Also, what is our branching strategy?  Are you having each developer create their own branch in the repo, which you will then merge into master?

Or are you taking a different approach?

**Comment by daver78** [comment]
@coa0329 tagging you in case you can answer before @paweenwich

**Comment by coa0329** [comment]
master is the branch for production.
stage is the branch for stage.
the rest are the branch create from stage.

**Comment by daver78** [comment]
@coa0329 OK, I'm using:
`git pull origin stage`
... to pull from stage.  What are you using to push back to the stage branch?

**Comment by paweenwich** [comment]
@daver78  Yes.    Please be aware that we are git newbie.  We are not sure either that this is the way that we suppose to do.   So, any suggestion from you are very welcome.

**Comment by daver78** [comment]
Take a look at: https://www.atlassian.com/git/tutorials/comparing-workflows

Which of these do you think suits us best?

**Comment by paweenwich** [comment]
@daver78 I think, what we are trying to do similar to the "Git Workflow".   We have master.  Our stage branch right now is similar to develop branch in the workflow.  So, I think this one will do, until we have more experience.
