### ISSUE TITLE
Should we consolidate to one repo?

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#113]
@paweenwich I think you or @coa0329 created two GIT repos at the start of this work because you were newbies.  

However, I think we would be better served by consolidating into one, which would allow us to tie your Issues, Pull Requests, Projects, Branches, and Code into one centralized area (instead of two).

Do you agree?

If so, I think the easiest thing to do is use `BhaangWeb` as the repo, and start adding our new issues there only.

**Comment by coa0329** [comment]
We should use BhaangWeb as the repo and we should put new issues there.

**Comment by coa0329** [comment]
This issue was moved to coa0329/BhaangWeb#2

**Comment by paweenwich** [comment]
Agree, on using coa0329/BhaangWeb

**Comment by coa0329** [comment]
https://github-issue-mover.appspot.com/

We can use this tool to move the issues between repo but the issue number will change.

**Comment by paagla123** [comment]
We're moving - closing this.
