### ISSUE TITLE
Email2 must have a schedule later than email1 and so on.

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#115]
Currently you can schedule emails 2 & 3 to go out before email1, or email 3 to go out before email 2. That  is incorrect behavior.

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
This is fixed - thank you. The pop up message needs some love. @daver78 you have suggestions?
![image](https://user-images.githubusercontent.com/29718335/30725251-1a422f3a-9ef8-11e7-9156-5c328931ceaa.png)

![image](https://user-images.githubusercontent.com/29718335/30725281-6ba6b6ac-9ef8-11e7-9b2c-2f933a11d48a.png)

![image](https://user-images.githubusercontent.com/29718335/30725289-7e749858-9ef8-11e7-8773-5c9fa408afb0.png)

**Comment by daver78** [comment]
@paagla123 Yes I have another task for this I think.  Let me assign it to myself and double check.
