### ISSUE TITLE
Form spilling out on the right hand side in screen where you create landing pages for eBook

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#117]
See screenshot here:
![image](https://user-images.githubusercontent.com/29718335/30527733-a7cbb170-9be0-11e7-838a-8592b9f91089.png)

**Comment by daver78** [comment]
Let's put new items in b-web. I anticipated this particular issue and have two solutions. Let's discuss before we choose a path.

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#14

**Comment by paagla123** [comment]
Moved to BhaangWeb

**Comment by paagla123** [comment]
@daver78 @paweenwich this issue still exists on smaller screens. Any ideas please?

**Comment by daver78** [comment]
@paagla123 What size viewport are you at?  Put a screenshot please?

**Comment by paagla123** [comment]
@daver78 remember to try this on an iPad

**Comment by daver78** [comment]
@paagla123 OK, I will.

**Comment by paagla123** [comment]
Moving to post Martech.

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#63
