### ISSUE TITLE
[PABP: Step 1] HTML shows GIT merge conflict notation

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#119]
The message below appears when you merge branches and do not resolve a conflict.  @paweenwich should resolve them during the merge.

For now, just remove it from the HTML -- but going forward, watch for these during merge.  Git will notify you.

![image](https://user-images.githubusercontent.com/29718335/30760554-86b43bd0-9f8f-11e7-92ca-ac5a7ec527ea.png)

**Comment by daver78** [comment]
@paagla123 I cleaned up the issue description for you.
