### ISSUE TITLE
Overall code architecture.

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#12]
* All pages are coded in php.  (Some page might still in html (login.html), we will change them all eventually).    Each screen will have it own php, for example, login.php, editPromoteBlog.php, welcome.php .. 

* We split into each php to make it easier for dividing the task to individual staff.  The draw back is that we need to maintain css and include wrapper (top,left) part for each page.   I am planning to change them to DV.php  style when we have all necessary feature is finish. 

*We have 2 kind of phps.  UI PHP and Logic PHP.  

*Logic PHP will have no HTML markup and will be called via AJAX by UI PHP.   The example of these PHP are  backen.php, getEmailTemplate.php, login.php

*UI PHP will have very little PHP (at the top) and the rest are mostly HTML markup.  We try to avoid mixing the PHP tag in the HTML.   So, 95% of HTML is clean.  

*Right now all working code is under /admin
- /admin/maml contain template MAML for rendering.  
- /admin/templates/emails contain email template for editing email
-/admin/publish contain backup of MAMLs before sending to studio.  

*database is CouchDB, can be access at http://web2xmm.com:5984/_utils

*config files are kept in database namd "master" (http://web2xmm.com:5984/_utils/database.html?master)
- Default_promoteBlog file contain all default value for promoteBlog blueprint.
- templates file contain configure information.  Ex. blueprints field contain list for blueprint known to system and default file.  Email field contain list of email template and location. 

*AngularJS is use for 2-way binding between JavaScript Object and DOM Object(UI).   Most of the data is managed by AngularJS.  However, there are a lot of UI component that can not do the "Angular way" directly.  Then, normal JQuery code is used to transfer data between JavaScript Object and DOM.  That means we need to put more code to load/save.(A*)

*We have another git that daily sync with the server.   https://github.com/coa0329/BhaangWeb
Please take a look the code at that instead of this git.    The reason for that is we need to backup the all server code and the current git have different directory structure and I am really git newbie.  So, I end up creating another git.  Sorry, for this inconvenient.     We still like this git (Bhaang) to keep document , issue, mockup.  We like to keep those git(BhaangWeb) as a full server's code backup.    

*Each account will have it own database.  For example, CampaignLauncher (228) will have database name as DB228.   Ex http://web2xmm.com:5984/_utils/database.html?db228

*Creating a new campaign will result in single document in each database.   The name of document is MD5(campaignName).   Ex http://web2xmm.com:5984/_utils/document.html?db228/771923bdc7e88602383a31bd390b6bed

*Userinfo keep data from accountSetting page

*CampaignLists keep list of all campaign and it's status (like master table)

*audienceLists  keep audiences data of this account

*backend.php will render data from database  + T-MAML in to final MAML.  While doing so, it also create file at S3 if necessary ({{URL xxx}}).   Then it will publish to studio.  

(A*)  This should partially explain why we have not use all UI from the mock up yet.  I told our staff to make software work before make look exactly like the mock up.  For example, mock up using PRETTY-UI, however, we have trouble integrating it.   Either, css,,js ,jquery version conflict and can not fix the problem easily then they should use more SIMPLE angular ready UI instead for this version.   

Eventually, all DV mock up will be there, please hang on :).

I hope this should answer most of Dave's question.

**Comment by daver78** [comment]
@paweenwich, great details.  This is exactly what I was looking for.  Everything you've stated makes sense.  Just a few questions:

1) What is an example of “_there are a lot of UI component that can not do the "Angular way" directly_"?

2) Regarding two git repos, I have no problem with that.  We can view BhaangWeb as our "real" code and this repo as the mock-up repo.  Yes?

3) Regarding some of my mock-up not being angular ready/friendly, I should have thought of this ahead of time.  I will start to make subsequent mock-ups 'angular ready'.  Good?

**Comment by paweenwich** [comment]
Basically, all UI component are not "Angular way" UI.   For example, SummerNote.    In order to init/get/set HTML in/out of the component we need to call the appropriate API.  
For example, get html out need to call 
var markupStr = $('#summernote').summernote('code');  
and a few code to set these value to JSON tree, before save to database.  Different UI need different function.  

While the "Angular way" (Angular supported) component, what we need to do is only add ng-model arrtibute.   Ex, summernote (luckily, we found the angular wrapper code on from internet at
https://github.com/summernote/angular-summernote)

So, we only need to put this new tag
<summernote ng-model="EMAIL1-HTML"></summernote>

Angular, will do everything from initial to 2 way binding the javascript field "EMAIL1-HTML1" with the component.   No, additional code is needed.  When we populate/update the "EMAIL1-HTML1", the UI will automatically be updated and when the HTML is update by user, the "EMAIL1-HTML1" is automatically update also.   

In theory, we can make any UI component into angular support component by putting wrapper code (Like angular-suummernote).  However, I am also a AngularJS novice.  I can not make the wrapper by myself yet :(.

**Comment by daver78** [comment]
@paweenwich I'm closing this issue and adding your notes to the wiki.
