### ISSUE TITLE
eBook Emails need their own template (subject says BLOG POST - should say eBook)

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#121]
See screenshot below: both emails please.
![image](https://user-images.githubusercontent.com/29718335/30765116-c490569c-9fa2-11e7-9a0c-bdf148a24275.png)

**Comment by daver78** [comment]
@paagla123 This isn't a bug -- we need a task to edit the default content for this blueprint (comprehensively). 

If you want, assign it to me and I'll do it.

**Comment by paweenwich** [comment]
@paagla123 @daver78  I need a direction on this one.  Right now, we shared the email template for all blueprints.  So, if we keep doing this, the template content should be generic (not specific to any blue print).    Or 

We make template to be blueprint dependent.  This way, the template can be more specific, however, we lost share ability.

Any suggestion?

**Comment by paagla123** [comment]
@paweenwich @daver78 I am pretty clear here - email template should be blueprint specific.

**Comment by paagla123** [comment]
@paweenwich please help me find the location where the default content for the eBook are kept - I ran out of time today, but I'd like to change them. Thank you.

**Comment by coa0329** [comment]
PromoteBlog
emails templates
BhaangWeb/html/admin/templates/emails/BLOG-COMPANY-EMAIL.html
BhaangWeb/html/admin/templates/emails/BLOG-PLAIN-EMAIL.html

pages templates
Welcome
BhaangWeb/html/admin/templates/pages/welcome/EBOOK-LANDINGPAGE-COMPANY-WELCOME.html
BhaangWeb/html/admin/templates/pages/welcome/EBOOK-LANDINGPAGE-COMPANY-WELCOME-2.html

Download
BhaangWeb/html/admin/templates/pages/thankyou/EBOOK-LANDINGPAGE-COMPANY-THANKS.html
BhaangWeb/html/admin/templates/pages/thankyou/EBOOK-LANDINGPAGE-COMPANY-THANKS-2.html

Default value
http://162.243.155.57:5985/_utils/document.html?master/Default_PromoteBlog
================
eBook

emails templates
BhaangWeb/html/admin/templates/emails/EBOOK-COMPANY-EMAIL.html
BhaangWeb/html/admin/templates/emails/EBOOK-PLAIN-EMAIL.html

Default value
http://162.243.155.57:5985/_utils/document.html?master/Default_PromoteEbook

**Comment by paweenwich** [comment]
@paagla123, A few thing that you need to know
1) [[REMOVE xxxx   ]]
This will exclude xxxx from Davinci view/editor, but keeping it for final render (email/landing page).
*after REMOVE need one more space

For example. 
```
[[REMOVE 
<HTML>
<HEAD>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script> 
	<script>
		$(document).ready(function() {
			$("#viewonlineRow").hide();
		});	
	</script> 
</HEAD>
<BODY>
]]
```

Davinci edit will not see <HTML><HEAD> ... 

2) {{RAW FIELD_NAME}}
This will render value in FIELD_NAME with out doing any HTML encode.    Without "RAW", it will do HTML encode the value first.

3) {{RAW SUMMERNOTE(LANDINGPAGE-FORM)}}
the SUMMERNOTE() will wrap summernote tag around the content to make it editable by simmernote UI.

**Comment by daver78** [comment]
@paagla123 Are you going to make edits?  You comfortable with your environment + git?

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#102
