### ISSUE TITLE
eBook Auto publish happening even when there is no change

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#124]
@paweenwich may be you should do a hash comparison or something similar to evaluate anything has changed or not and then checkout and publish. Now the system publishes when I just click the save button, even if nothing has changed.
Also - no need to publish for content changes in S3 - right?

**Comment by paweenwich** [comment]
Ok, we will try to optimize the save/publish process.

**Comment by daver78** [comment]
@paagla123 and @paweenwich Are we publishing even for changes to S3 content?

**Comment by paweenwich** [comment]
save optimized  
(not save if no change)
 but still always publish and upload items to s3

**Comment by paweenwich** [comment]
check in optimized done
(not check in if MAML is not differ than previous one)
but still always upload item to S3

**Comment by paweenwich** [comment]
Finally, all done.

**Comment by paagla123** [comment]
@paweenwich it seems you have stopped publish, but you are still enabling edit.

**Comment by paagla123** [comment]
@paweenwich you are enabling edit first, then checking the content and deciding not to publish if there is no change. In the process the MAML is left checked out. You should either not check it out at all (if possible), or if you decide not to publish, undo checkout.

**Comment by coa0329** [comment]
@paweenwich fixed it.

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#101
