### ISSUE TITLE
Domain for microsites - eBook and Blog

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#125]
Let us use dvNNNNN.m.mdl.io for domains associated with each acct, where NNNNN stands for the account id. Use dvNNNNN.m.mdl.io/xxxxx for each microsite, where xxxxx is the campaign id as stoded in couchDB. 
Right now I have created:
Campaign launcher: dv228.m.mdl.io
Davinci: dv16916.m.mdl.io
Davinci for Atrium: dv17124.m.mdl.io ( @coa0329  - were you thinking along the same line?)
Davinci for Mary: dv17118.m.mdl.io

I have a campaign called KD-eBook-0922-Stage-004 under daVinci acct with an ID of 9c29ea93861c279594a371f89b85e069.Domain associated with the microsite for that campaign will be:
http://dv16916.m.mdl.io/9c29ea93861c279594a371f89b85e069 

In future, the sign up process will create the main domain under the acct - right now its manually done. The system will generate the microsite domain by appending the ID while publishing.

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
@coa0329 we have issues for Blog - see issue #129

**Comment by coa0329** [comment]
Fixed on stage for eBook.

Please create the new campaign when you test.
