### ISSUE TITLE
eBook trigger email in eBook schedule does not change even when changed in the config

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#127]
Email2 changed schedule in DaVinci:
![image](https://user-images.githubusercontent.com/29718335/30767707-09ebb25c-9fb4-11e7-804f-be49e9da41a7.png)

In published Studio program still shows 1 hour:
![image](https://user-images.githubusercontent.com/29718335/30767719-1f337c26-9fb4-11e7-85ef-2dd445ddd260.png)

**Comment by daver78** [comment]
@paagla123 Did you republish in DV?

**Comment by paagla123** [comment]
@daver78 yes several times.

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
Works now in stage
