### ISSUE TITLE
Show studio error and convert to friendly version.

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#13]
- Try catch all API error and show to user (by trying to map it to friendly version first)
- map should implement in json for easy editing.

**Comment by paagla123** [comment]
Coa - do you have a list of errors you have received so far? If not, can we go back and create one please?

**Comment by coa0329** [comment]
@paagla123 
do you have a list of errors you have received so far? 
No, I don't.

If not, can we go back and create one please?
We can re-create some of them.

**Comment by paweenwich** [comment]
Show ErrorCode and ErrorMessage now

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#49
