### ISSUE TITLE
eBook Lead Trigger Content missing

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#131]
@daver78 you and I need to discuss this first - I just realized that this is not the same as blog.

**Comment by daver78** [comment]
@paagla123 OK.  I'm not sure what you mean?

**Comment by paagla123** [comment]
@daver78 we can talk tomorrow

**Comment by coa0329** [comment]
You can change the content of the triggers on S3

eBook
DownloadAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/ebook_downloadleadtrigger.html

VisitAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/ebook_visitleadtrigger.html

Promote Blog
OpenAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/promoteblog_openalert.html

ClickAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/promoteblog_clickalert.html

**Comment by paagla123** [comment]
@coa0329 Looks like I made a mistake in creating the MAML template. The Welcome page should be of Add Contact type for the contact to be saved and used in the lead trigger.  Only change is in the Property called PageType from the Welcome.html page. Pl see below and let me know if you ca take care of this.

What we have now:
         <ChildElement Id="16" RuleGroup="ContentVariables" DbId="0" Type="Page" IsVersion="False" Name="Welcome.html" Position="140,50">
            <Properties PageType="Page" IsHomePage="True" SkipPage="False" IsLoginRequired="False">

What we need:
         <ChildElement Id="16" RuleGroup="ContentVariables" DbId="0" Type="Page" IsVersion="False" Name="Welcome.html" Position="140,50">
            <Properties PageType="AddContact" IsHomePage="True" SkipPage="False" IsLoginRequired="False">

**Comment by paagla123** [comment]
@coa0329 I do not have access to the above htmls in S3. Looks like they have to be made Public.

**Comment by paagla123** [comment]
@daver78 what happens when someone creates a form that does not include the dedupe and the PURL generation criteria? Should we ask @AumpaiFung to change the form generation to have Minimum of Firstname, Lastname and Email in every form? These three fields in that case cannot be removed. Thoughts?

**Comment by daver78** [comment]
@paagla123 Awesome, I was waiting for this to get raised.  Few thoughts:

1) When a new sub-account is automatically created for a DV user, are we setting `email` as the only de-dupe?  I imagine in the future we have to make this configurable; but for now, I agree if we're tying this down to 1 field.

2) If `email` is the only de-dupe field, I think the only field we should require in the form is `email`.  We should create a unique number or alphanumeric value for `firstname` and `lastname` behind the scenes (`hidden` fields in the form).

Why?

As a marketer, there are many times where just collecting email in the first interaction is useful.  Asking the user for more may defeat the purpose of what the marketer is trying to accomplish.

Further, in the very near future, I want to enrich the form data from outside sources, such that by collecting `email `, we can automatically pull in the `firstname` and `lastname` values from other data sources (think ClearBit, D&B, LinkedIn, etc.).
