### ISSUE TITLE
URL for eBook

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#132]
@coa0329  it should be copied to the fields in landing page settings so that people can see it easily. Pl see screenshot below.

![image](https://user-images.githubusercontent.com/29718335/30891469-6e6920fc-a2e8-11e7-96c4-a1981036377e.png)

**Comment by coa0329** [comment]
Please explain more.

Do you want to put the correct domain in welcome page URL and Thank you page url ?

**Comment by paagla123** [comment]
Yes @coa0329 , the domain that is in Studio when the program gets published, appended by /Welcome.html or /Download.html as the case may be. Thank you.

**Comment by daver78** [comment]
@paagla123 and @coa0329 There are details in BhaangWeb -> [Microsite] Settings Requirements #27

**Comment by coa0329** [comment]
Fixed on stage.

**Comment by paagla123** [comment]
@coa0329 great work thank you. Can you please make the microsite open in a new tab when somene clicks on the link? Pl see screenshot below.
![image](https://user-images.githubusercontent.com/29718335/30930914-04332206-a378-11e7-83b2-9133c6db8fdf.png)

**Comment by coa0329** [comment]
Make the microsite open in a new tab when someone clicks on the link?
- Fixed on stage.
