### ISSUE TITLE
eBook the contact form can be submitted without filling in the required fields

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#136]
I created a form contact-kd under davinci acct and used it in eBook KD-0927-eBook-03. Welcome page link is http://dv16916.m.mdl.io/a9cf22047913822d77949feb00b55c96/Welcome.html?SessionGuid=07a31a96-7a92-4683-86d8-66c9ae3db078 . Firstname, lastname and email are required. I can submit the form without filling in these fields.

**Comment by paweenwich** [comment]
@paagla123 You have not told us anything about form validating/submission ... etc.  I though Studio, which host this will handle the required field as well as form posting.     Is there any easy way to do this without generating javascript code to check it?

**Comment by paagla123** [comment]
@paweenwich yes Studio will do it if you set the correct properties before publishing the MAML
Right now the code for First Name in the MAML is:
             < Input Type="TextBox" Name="First Name" IsEncrypted="False">
                <IsRequired>False</IsRequired>
                <ValidationRegex />
                <ValidationRegexMessage />
              </Input>

For validation it should be:
              < Input Type="TextBox" Name="First Name" IsEncrypted="False">
                <IsRequired>True</IsRequired>
                <IsRequiredMessage>Please Enter First Name</IsRequiredMessage>
                <ValidationRegex />
                <ValidationRegexMessage />
              </Input>

**Comment by paagla123** [comment]
@paweenwich @daver78 I am thinking that since we MUST have firstname, lastname and email, we should make them required in the MAML itself and in the form they cannot be removed. We make them required by default. Remaining fields we work out if required should be turned on or not.

**Comment by AumpaiFung** [comment]
@paagla123 
From link above >> ( http://dv16916.m.mdl.io/a9cf22047913822d77949feb00b55c96/Welcome.html?SessionGuid=07a31a96-7a92-4683-86d8-66c9ae3db078) 
It's not set require field so when click "Download Now!" will not required any field. 

Please try this! >> http://dv16916.m.mdl.io/0522b1b0a97d2bd443e02fa2f4928e8c/Welcome.html?SessionGuid=4c5d8a1b-a666-45f1-bb6c-9afa626d3500
This is Davinci stage, Campaign Named "AF -stage test" that had set required field in form. 

Notice: required field must has red start.

**Comment by paagla123** [comment]
@paweenwich How has this been implemented?

**Comment by paweenwich** [comment]
@paagla123 Right now we use bootstrap frame work to handle it.  You need to set which field is required in the form template via UI.  We did not touch Studio feature for <INPUT> in the MAML.
