### ISSUE TITLE
eBook Welcome page needs to be of type Add Contact

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#137]
@coa0329 Looks like I made a mistake in creating the MAML template. The Welcome page should be of Add Contact type for the contact to be saved and used in the lead trigger.  Only change is in the Property called PageType from the Welcome.html page - value to change from Page to AddContact. Pl see below and let me know if you can take care of this in the existing eBook template.

What we have now:
         <  ChildElement Id="16" RuleGroup="ContentVariables" DbId="0" Type="Page" IsVersion="False" Name="Welcome.html" Position="140,50"  >
            < Properties PageType="Page" IsHomePage="True" SkipPage="False" IsLoginRequired="False" >

What we need:
         < ChildElement Id="16" RuleGroup="ContentVariables" DbId="0" Type="Page" IsVersion="False" Name="Welcome.html" Position="140,50" >
            < Properties PageType="AddContact" IsHomePage="True" SkipPage="False" IsLoginRequired="False" >

**Comment by paagla123** [comment]
Referenced in #131

**Comment by coa0329** [comment]
Fixed on stage,
