### ISSUE TITLE
eBook Templates need to be made available

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#138]
@coa0329 @paweenwich I can see the Lead Trigger templates for Blog but not for eBooks. They need public permissions. Related to #131 . Please also let me know where the templates for landing pages (html) and Thank You emails are.

eBook
DownloadAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/ebook_downloadleadtrigger.html

VisitAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/ebook_visitleadtrigger.html

Promote Blog
OpenAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/promoteblog_openalert.html

ClickAlertLeadTrigger
https://s3-us-west-1.amazonaws.com/bkktest/template/promoteblog_clickalert.html

**Comment by coa0329** [comment]
Add permission to eBook trigger templates on S3.

===========

BhaangWeb branch stage.

Welcome Page
BhaangWeb/html/admin/templates/pages/welcome/EBOOK-LANDINGPAGE-COMPANY-WELCOME.html
BhaangWeb/html/admin/templates/pages/welcome/EBOOK-LANDINGPAGE-COMPANY-WELCOME-2.html

Download Page
BhaangWeb/html/admin/templates/pages/thankyou/EBOOK-LANDINGPAGE-COMPANY-THANKS.html
BhaangWeb/html/admin/templates/pages/thankyou/EBOOK-LANDINGPAGE-COMPANY-THANKS-2.html

Emails
BhaangWeb/html/admin/templates/emails/EBOOK-COMPANY-EMAIL.html
BhaangWeb/html/admin/templates/emails/EBOOK-PLAIN-EMAIL.html
