### ISSUE TITLE
Forms: Screen goes dark and cannot do anything (see screenshot)

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#142]
![image](https://user-images.githubusercontent.com/29718335/30988875-9ca40982-a450-11e7-87f7-0c75aab7e398.png)

To reproduce, drag a couple of fields over to the middle section. Now click on the setup icon (gear) . Ciick on fitstname to view th issue

**Comment by daver78** [comment]
@paagla123 I cannot repo.  Can you do a short video in case me and @AumpaiFung do something different than you?

**Comment by paagla123** [comment]
I showed @AumpaiFung last night

**Comment by daver78** [comment]
@paagla123 OK ignore me then :)

**Comment by AumpaiFung** [comment]
@paagla123   I can not reproduce also.

**Comment by AumpaiFung** [comment]
@paagla123 
We found that causes of when create new form.
1. First put cursor focus on Form Name input box.
2. Drag right field to the middle.
3. Press setting button of original field.
Then the dark screen occured.

I fixed it on Stage. 
**NOTE** Please beware cache.

**Comment by paagla123** [comment]
@AumpaiFung @paweenwich @coa0329 this is working well. Ready for production. I am going to close this. Thx
