### ISSUE TITLE
Image doesn't display in email.

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#16]
Image doesn't display in email.
![086](https://user-images.githubusercontent.com/7914690/29711396-c3ce42e0-89be-11e7-834b-89c6f45c706a.JPG)

**Comment by daver78** [comment]
@coa0329 and @paagla123, by the way, it seems real contact from MindFire Master got this email.  How did that happen?

**Comment by coa0329** [comment]
The first few tests we did some mistakes in setting the filters in the maml before publish,  so emails will send to all contacts. 

The issue is fixed.
