### ISSUE TITLE
Update Lead Alert email with slightly sexier template

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#18]
@paagla123, see `lead_alert_email.html` which I checked in today.  Can you update your MAML template(s)  with this instead of what you have now?

Few things:
1- You may want to consider *NOT* hard coding your HTML for the triggers like you do now. If we put the HTML on S3,  we can edit the triggers and alerts so that when we roll out improvements to them, everyone benefits immediately. Otherwise, people will be stuck with old format.

What think?

2- In the future, I'll want to give people a way to either (a) edit the layout of the trigger/alert, or (b) add their own information into the lead alert (e.g., they may want to include a special message to their sales team, and/or some other ##fields## into the alert to make it more relevant to their biz)

No action required, just FYI.

3- I think we need a way of referencing the DV Campaign Name and Email in the lead alert so we can say something like: Bill Gates opened EMAIL NAME in CAMPAIGN NAME. Do we have a syntax for this?

![da-vinci-rules_trigger_email](https://user-images.githubusercontent.com/7561473/29731697-481f42e4-899a-11e7-9935-403823d39be4.png)

**Comment by coa0329** [comment]
@daver78 you can use {{campaignName}} for it.

**Comment by daver78** [comment]
@coa0329 OK.  Is there anything that we can use to identify the specific email?  Like a name, it's subject, etc.?

**Comment by paagla123** [comment]
We'll come up with a way to name the elements. Re the triggers,  we can put in s3.

**Comment by daver78** [comment]
@paagla123 OK will you update your T-Rex?  I mean TMAML.

**Comment by paagla123** [comment]
@daver78 Yep. I need to co-ordinate with @coa0329 - we'll deal with it in the morning

**Comment by daver78** [comment]
@paagla123 Is this done?  Please confirm.

**Comment by paagla123** [comment]
@daver78 not quite.
@paweenwich I have a version 8 of the MAML now that was created after talking to Coa. It fixed all the issues he and I noticed, with the exception one that I logged separately. Can you please start using the ver 8 moving forward?

**Comment by coa0329** [comment]
I put version 8 on the server.

**Comment by paagla123** [comment]
Thanks @coa0329 . Once you fix #41 please let me know - I will test both together and close both of them. Thanks - Kushal

**Comment by paagla123** [comment]
This is done. Closing it.

**Comment by daver78** [comment]
@paagla123 Excellent.
