### ISSUE TITLE
Thoughts on Forms (and DV Smart Forms)

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#19]
@paagla123 , read the wiki post here: https://github.com/coa0329/Bhaang/wiki/Da-Vinci-Smart-Forms.

Let's discuss when ready.

**Comment by daver78** [comment]
@paagla123 By the way, you may be wondering: Why not an off-the-shelf or pre-written form builder?

Fair question.

I've looked at roughly 20-30 of them.  They all have pros/cons.

But the biggest issue in my mind is the user experience, and while some of them are configurable, I don't think any of them fit nicely into the flow of what we're trying to do.

The ones I've looked at are generic form builders, constructed from the POV of general form building.

Our scenario, while on the surface appears similar, has some difference I think.

That's why I'm suggesting we build a lite interface for form building that is specific to our needs.

If it sucks, we'll kill it.

If it's good, we'll mature it.

**Comment by paagla123** [comment]
@daver78 This is good - I really like it. I have had the same dilemma - the form builders seemed too complex in spite of all the hoopla (just a word I made up - hope it carries its own meaning)! I think the question we need to answer is what should we do if a user wants to place the form on the right side of the screen and not left, or should that become another template?

Re your question " Can the form be a ##URL## var too? Or does this not work in Studio? " who are you asking this?

**Comment by daver78** [comment]
@paagla123 My thought on how to address what you've stated is to simply make it another template (form on left, form on right).  They can experiment with which one brings better conversions (and we should eventually provide some data on this).  

Re my question, do you know the answer?  If not, I'd like to get @jvoigt in here to answer.

**Comment by paagla123** [comment]
@daver78 I don't. We need to ask Jason. We can do a variable within a variable I think. In any case, I am ready to discuss this if you want to. Thx

**Comment by paagla123** [comment]
@AumpaiFung is now assigned to build a prototype for this. We will integrate into the main da Vinci after Print 17. For now it will be launched from the menu using "Asset Library" option. Only Form and Page libraries need to work before Print 17. The page library should have capabilities of saving the html.

**Comment by paagla123** [comment]
@daver78 we should be able to add a Form Asset into a Page Asset. The code being developed by @AumpaiFung should have the capability of saving the html from the Page Asset into the local drive.

**Comment by daver78** [comment]
@paweenwich Do you want to close this one, and open one specific to the work @AumpaiFung is doing?

**Comment by daver78** [comment]
@paagla123 Do you want to close this one, and open one specific to the work @AumpaiFung is doing?

**Comment by paagla123** [comment]
@daver78 no - she can work off of this one. I may change that opinion once I talk to her tomorrow

**Comment by daver78** [comment]
@paagla123 I'm going to close this one and let you open subsequent Issues based on your review of @AumpaiFung's work.
