### ISSUE TITLE
Da Vinci Campaign Names (non-unique) mapped to Studio Program Names (unique)

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#20]
Need to check before allow program to create if the program name is duplicate

**Comment by paagla123** [comment]
My thought on this is to differentiate between program names in Da Vinci that users use (may have duplicates) vs Program Names in Studio, which probably should be internally created by us with a combination of what user typed plus time stamp. In my opinion, we should not bug end users with creating unique names - we should be able to handle that programmatically. What do you all think? Just a suggestion.

**Comment by daver78** [comment]
**@paagla123 YES!  PAAGLA for the win!**  

This is what we need to do.  If you look at 'modern' apps like Google Docs, the User is not required to make a unique name for their stuff.  Certainly, Google does that behind the scenes for them, but the User, as Kushal says, is not bothered with such mental overhead.

**We should do the same.**

I handled this in my mockup by delimiting the name entered by the user from the current moment's epoch time, thus providing Studio with a unique name.  

So if you create a campaign with the name "Coa", Studio Program name would be:

`[DV]Coa[DV]1503858790`

When making the API call to Studio to get Published Programs to display to the user, I `explode` based on `[DV]` to show the user the name they entered.

Can we plz do something similar?

**Comment by paagla123** [comment]
Yes @daver78 - only question is how will show up in the dashboard. We probably have to keep our own mapping of that - right?

**Comment by daver78** [comment]
@paagla123 We could, or just do what I did above when displaying it back to the User.  I'm sure @paweenwich will have a suggestion.

**Comment by paweenwich** [comment]
@daver78 Do we care if the publish program in studio has GUID name or "User name program + timestamp"..  In the other word, do we expect user to login Studio and see those strange name?  

If not, we can 
1)  name it with hash function like MD5() or GUID() and keep the mapping.  
or 
2) keep user program name and suffix with timestamp (Dave's trick).   We can keep the mapping or expload() 

I think it depend on how we like to see it in Studio.

**Comment by paagla123** [comment]
We don't expect the users to log into Studio.

**Comment by paagla123** [comment]
We have decided to deal with this after Print17

**Comment by daver78** [comment]
@paweenwich I agree with @paagla123 -- I'm not that concerned about what the User sees in Studio.

**Comment by paagla123** [comment]
I have renamed this issue to distinguish fro the issue of checkout/checkin/republish with the same program name which will have to be addressed before Print17. There is still an outstanding issue of da Vinci users giving wild-ass names that will get mapped to unique names in Studio - not necessary for Print17. @daver78 @paweenwich do you guys agree?

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#48
