### ISSUE TITLE
Give me the ability to invite other collaborators

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#21]
@coa0329, can you give me the necessary permission(s) to invite a few other people?

For example, I'd like Jason to be able to watch the conversations so he gets up-to-speed with what we're doing.  I may invite RF at some point as well.

**Comment by coa0329** [comment]
@daver78 I cannot find where to set you to be the admin.

Please put their github id here. I will send them the invitation.

**Comment by daver78** [comment]
javpowell

**Comment by coa0329** [comment]
I email him the invitation.

**Comment by paagla123** [comment]
@daver78 please ask Jason to accept invitation. Thx
