### ISSUE TITLE
Copy Campaign feature doesn't work yet

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#25]
Copy Campaign does not appear to do anything

**Comment by daver78** [comment]
@paagla123 In your opinion, not required for P17 -- correct?

**Comment by paagla123** [comment]
@daver78 Yes.

**Comment by paweenwich** [comment]
done on stage.
http://davincistage.mindfireis.com/

**Comment by paagla123** [comment]
@paweenwich this is good thanks. I will test it thoroughly.

**Comment by paagla123** [comment]
@daver78 @paweenwich  this works fine. But I would contend that copy campaign feature should copy everything except the audience and schedule. Otherwise schedule may be in the past.

![image](https://user-images.githubusercontent.com/29718335/30527405-03155ab2-9bdd-11e7-9148-c68ee23625b5.png)

**Comment by daver78** [comment]
@paagla123 I think I agree.  Let's do as you suggest and then try it on when you run your real campaigns for @Mcfarsheed?

**Comment by paweenwich** [comment]
Done.
