### ISSUE TITLE
We should allow email schedule for 2nd email onwards to go down to 0 days. Currently it stops at 1 day.

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#26]

**Comment by daver78** [comment]
@paagla123 and @coa0329 Agreed.  Oversight in UI.

@paagla123 This raises another item: Once the date/time has passed for the initial blast, that schedule should no longer be editable.  True, false?

**Comment by paweenwich** [comment]
The 0 days can be set now.

**Comment by paagla123** [comment]
DONE! CLOSED!!
