### ISSUE TITLE
We cannot publish programs in daVinci account, but Campaign Launcher just works fine

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#27]
@daver78 - @coa0329 claims that some special permission is needed for account to be able to publish from API. I was not aware, but Coa must know, since he has done it before. Can you please get Jason to look into it? Acct ID is 16916. Thx

**Comment by javpowell** [comment]
This should not be the case, the User permission in Studio is what controls access. The API Partner/Pass do not limit access. Maybe the user does not have permissions inside the Studio->User Management->Roles 
    (https://www.screencast.com/t/CHi4JTU9wo)

**Comment by javpowell** [comment]
That, or they have not been given permission to the Program itself https://www.screencast.com/t/CHi4JTU9wo

**Comment by paagla123** [comment]
@javpowell can you please shed some light on this?

**Comment by javpowell** [comment]
I responded, do I need to have more input here?

**Comment by coa0329** [comment]
Fixed.

It is the bug in get ticket function.

**Comment by paagla123** [comment]
Fixed by Coa. Wrong ticket used.

**Comment by daver78** [comment]
@paagla123 Now who was smoking something?  @javpowell is vindicated.

**Comment by javpowell** [comment]
Only the best Bhaang


*Jason Voigt*
*Client Services Manager*
jvoigt@mindfireinc.com | *949.579.9840*
http://www.mindfirestudio.com/
