### ISSUE TITLE
Double byte characters mess up email content

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#28]
I tried with Thai characters - email was totally messed up. @paweenwich may have fixed something, I will retest. Not important for Print17

**Comment by daver78** [comment]
@paagla123 As mentioned on phone, my gut tells me this is a Studio platform issue.  If you can provide @javpowell with the test steps and asset(s) to repo, he can have someone verify.

**Comment by paagla123** [comment]
The characters supposed to be in UTF-8 encoding.
@paweenwich can you please check?
https://bkktest.s3.amazonaws.com/tmp/TEXT-AREA-228-a4fe27ca642b5096dbbb09b7913a3cca-EMAIL1CONTENT.html

**Comment by daver78** [comment]
@paagla123 I thought you said that in the S3 HTML, the chars show up OK?  Is what I'm seeing in the s3 file OK or NOT OK?

**Comment by paagla123** [comment]
Came through fine on Outlook - seems a gmail issue. Need to test more

**Comment by paagla123** [comment]
Works well now. Closed.

**Comment by daver78** [comment]
@paagla123 What was the issue?

**Comment by paagla123** [comment]
@daver78 I'm not 100% sure - there were lots of issues with email content yesterday and Kwang was working on them. This may have been fixed as part of that. I tested several scenarios and it works - so closing it now. We will have to start a regression suite in future and include it in that.

**Comment by daver78** [comment]
@paagla123 I suggest someone start creating selenium test cases -- soon.  Let the UI mature just a little more.  Who do you think is the right person on the team?

@javpowell adding you just as FYI.

**Comment by javpowell** [comment]
Hey Dave,

Lets chat about the "State of QA" again. Things kinda got halted a while
back but really it sounds like with Da Vinci and Purl Services + Microsite
Version 2.0 there will be ample QA needs. Now more than ever we may need to
get back to finding someone for this work, theres no way I will be able to
do it all.

Thanks,
Jason


*Jason Voigt*
*Client Services Manager*
jvoigt@mindfireinc.com | *949.579.9840*
http://www.mindfirestudio.com/
