### ISSUE TITLE
Need ability to update and republish an already published campaign without having to publish a new program

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#29]
Agreed today that during the initial publish the program id will be retrieved and kept in a database along with Studio program name and daVinci campaign name. We will use this program later on to call checkout and checkin APIs of Studio to republish. 

As a note, because of the S3 approach, we don't need to republish just for content change. We need to republish for changes due to schedule add/update and alternations in target audiences.

**Comment by paagla123** [comment]
@paweenwich this issue is related to #20 as well. We can probably close one of them.

**Comment by daver78** [comment]
@paweenwich and @paagla123 should we close this one or #20?

**Comment by paagla123** [comment]
On second thoughts, they are related but #20 has additional items. I would leave both open.

**Comment by paagla123** [comment]
@paweenwich a great example is the campaign Kushal Blog 10202 under DaVinci account. I have set up 2 emails and both have been sent. I now want to go back and set up and send the 3rd email. THis is a great example of where we should do a checkout, update and checkin to add the schedule. 

I noticed that the way this code is done, it will require a publish even for content update. Instead of pointing to S3 for the content of Email3, it has something called MISSING-TEXT-AREA-ACCTID-PROGRAMID-EMAIL3CONTENT. This actually makes matters worse - I hope you agree.

**Comment by paagla123** [comment]
@coa0329 MAML v9 is done as you requested. Dave's html for triggers in there too.

**Comment by coa0329** [comment]
I updated the MAML v9.

**Comment by daver78** [comment]
@paagla123 Help me understand how `MAML v9` addresses the "Need ability to update and republish an already published campaign without having to publish a new program"?

Or is it unrelated?

**Comment by paweenwich** [comment]
@daver78 Right now, we can publish the MAML by convert MAML to manually craft T-MAML (MAML with {{xxxx}}) in side.   So, we can easily put data into {{xxxx}} and correctly publish.     To republish, the major problem is that we don't have {{xxxx}} to replace anymore.  When we checkout, we get real MAML.  So, we ask KD to name element in MAML to something that we can locate and change easily.  For example, something like EmailXContact, EmailX, EmailXSchedule   (X is 1,2,3 .. )  instead of Contact1, Email1, FirstSchedule.

**Comment by paagla123** [comment]
@coa0329 @paweenwich what is the update on this. We have to have this done before the Trade Show. Thx

**Comment by coa0329** [comment]
Fixed
You can launch the campaign then re-launch it.

Promote a Blog Post
- Set up new email, Change email
- Change schedule

Working on select audience.

**Comment by paagla123** [comment]
Working well so far - been able to add 3rd email after publishing the first two. Will test more before closing.

**Comment by paagla123** [comment]
Working well. Closing. Will open new issues if something comes up.

**Comment by daver78** [comment]
@paagla123 You're 100% clear how this is working and can explain it to me tomorrow?  (For purposes of what we should do in the UI)

**Comment by paagla123** [comment]
@paweenwich working on contact filters and others related to republish.

**Comment by coa0329** [comment]
Fixed

Promote a Blog Post
- Choose Your Audience
- Open my Emails
- Visit my Blog Post

**Comment by paagla123** [comment]
@paweenwich @coa0329 @daver78 I am ready to close this issue

**Comment by daver78** [comment]
Closing for @paagla123
