### ISSUE TITLE
Filter render when publish.

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#3]
We should not do xmlencode for filter.

Example

&lt;Filter CriteriaJoinOperator=&quot;&amp;amp;&quot;&gt;&lt;Criteria Row=&quot;1&quot; Field=&quot;email&quot; Operator=&quot;NotEqual&quot; Value=&quot;&quot; /&gt;&lt;/Filter&gt;	

should be

<Filter CriteriaJoinOperator="&amp;"><Criteria Row="1" Field="email" Operator="NotEqual" Value="" /></Filter>

**Comment by paweenwich** [comment]
Done, by implement {{RAW XXXXX}}  to indicate RAW (not html encode) when render.
