### ISSUE TITLE
List of MUST HAVE features for PRINT17

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#30]

**Comment by paagla123** [comment]
Home: No changes

Create a campaign: Bring in the page that Dave has in the daVinci prototpe in C9.
	First two products should be the Blog and the eBook.
	Remaining products should be grayed out and non-clickable
	
Audiences: No changes except related to issue#9

Asset Library: Form builder, page template buikder - these two must work. Page builder must be able to download the resultant HTML.

Products: Email Blog - do up to three emails, reoslve all issues
		  eBook: Basic stuff should be done

**Comment by daver78** [comment]
@paagla123 Can you break this down into discrete tasks, now that we've discussed?

**Comment by paagla123** [comment]
@daver78 its all done in the other issues - isn't it?

**Comment by paagla123** [comment]
Here's a complete list as on 6PM BKK time Fri 9/1:

#11 - Sync UI with Dave's daVinci
#29 - Update and republish
#34 - Promote eBook
#36 - Forms
#37 - Page builder
#39 - Image cleanup
#41 - Notifications and Alerts
#52 - Change page title
#57 - MISSING-TEXT-Line...
#58 - Call to action button
#60 - Login screen
#61 - Images not showing in email

#37 will be a stretch it seems. We need to be done by Web of next week so that we have a few days to test. Most of these are bugs with eBook - so we must be able to resolve them. New features are eBook and the Form+Page builder.

**Comment by javpowell** [comment]
Any of these specific to me I should put attention to?

**Comment by paagla123** [comment]
OPEN from BEFORE
#11 - Sync UI with Dave's daVinci: @paweenwich @daver78 - any update here?
#29 - Update and republish: @paweenwich @coa0329 - please provide update.
#34 - Promote eBook: @jiewsone please provide update
#36 - Forms - @AumpaiFung pl provide status
#37 - Page builder
#39 - Image cleanup: @paweenwich @coa0329 Any update here?
#57 - MISSING-TEXT-Line... - @coa0329 status update please
#60 - Login screen: @paweenwich @coa0329 who is assigned to sync these screens?
#65 - Question for eBook
#68 - Promote an eBook Product Image
#72 - show user's firstname on topwrapper

CLOSED Issues:
#41 - Notifications and Alerts - CLOSED
#52 - Change page title - CLOSED
#58 - Call to action button - CLOSED
#61 - Images not showing in email - CLOSED
#62 - Display of most recent campaigns not correct due to not accounting for time zone - CLOSED
#63 - No HREF in the CTA link in the PLAIN EMAIL - CLOSED
#69 - editpromoteblog.php: the font has changed and the text wraps - CLOSED
#70 - myCampaigns.php now missing last modified time stamp - CLOSED
#71 - html code shows up in the emails delivered using PLAIN template - CLOSED

**Comment by daver78** [comment]
@paagla123 regarding #11, I think you should close that Issue.  I will continue to do love to the UI, and if there is something specific the team needs to do, we will create an Issue for it.  Do you and @paweenwich agree with this approach?

**Comment by paweenwich** [comment]
I think we should close #11.   Dave already takes over this one.

**Comment by daver78** [comment]
@paagla123 and @paweenwich Do we need this Issue and list still?  I think we can work for the Issues list with filter by Milestone and get same.  Let me know?

**Comment by paweenwich** [comment]
I usually look at issues list.  :)

**Comment by daver78** [comment]
@paagla123 you ok if we deprecate this?

**Comment by paagla123** [comment]
Yes - I will close.
