### ISSUE TITLE
Print17 Promotion & Messaging Plan

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#32]
@paagla123 As is expected, the sales team is very excited to demonstrate DV.

Having been through this before many times now, I want to be very careful how we position this to our team and the market.

I'd like to have a session to discuss with you and Mackenzi the following items.  Perhaps you can give some prelim thoughts in advance of our meeting.

1- Each day, we have two 25-minute educational sessions that we invite prospects & clients to.  Mary and Joe would like to feature DV in this presentation as the main focus.  Thoughts?

2- When people say, "Is this ready?" or "Can I sign up now?" or "How much will it cost?" or "When will it be ready?" ... we need to have answers that are approved by you and me.  No going rogue.

3- @javpowell I'm sure you'll have questions too.  What are your thoughts?

**Comment by paagla123** [comment]
Mary and Joe would like to feature DV in this presentation as the main focus.: I don't agree. We must remember why we are doing this - it is to retain the low end of the customers. Studio is our main differentiation - there are lots of people that do the daVinci stuff. This is a leadgen cum improve retention tool. 

Besides, don;t forget that we will have teh new formgen tool, which should help a lot. 

I suggest we create a group of prospects that really need this type of product - don't want to undersell to someone who can deal with Studio - right?

**Comment by daver78** [comment]
@paagla123 While I agree with you re: not making it the main focus, I think it is for different reasons.  However, we come to the same conclusion either way.  

So, I will tell them to focus on something else (although we can certainly touch on DV).

That said, when we speak tonight, remind me to talk to you about your reasoning.

**Comment by daver78** [comment]
We are going to discuss the details of "unveiling" on Tuesday.  Dave to send invite.

**Comment by daver78** [comment]
@Mcfarsheed see above for history of this conversation.  At this point, I've decided that **NO, we will not make it the core focus of the edu sessions**, but we can certainly touch on it.  

We will discuss further on Tuesday, but for now, can you make sure this is clear to everyone?

**Comment by paagla123** [comment]
Closing this one now
