### ISSUE TITLE
Review "Promote an eBook" Blueprint for implementation

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#34]
Promote an eBook is ready for analysis.  Example here:

https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php?page=PAEB_homePage&programNameHash=633269bbc183cd5b4943358130e38bb0

@paagla123, here's what I think is "ready" in each section:

- **Configure your eBook**: Ready

- **Set Up Your Landing Page**: 

* **Welcome Page**: Likely go-live with just one template (2nd one in list)

* **Thank-You Page**: Likely go-live with just one template (2nd one in list)

* **Landing Page Settings**: Missing a few meta fields; I can add them tomorrow if urgent

- **Write Your Auto-Responder Drip Sequence**: I now realize this UI is different than this section in "Promote a Blog Post".  

Do you spot the difference(s)?  

Not sure which is the right approach.  Should we mirror what we did in Promote a Blog Post?  If so, the UI needs to be changed and another "step" added to the accordion.  Please give me your thoughts and let's be clear before we implement.

- **Configure Notifications & Alerts**: Ready

PS:  We've agreed that in this one, we're going to eliminate the need for "Publish" unless absolutely necessary.  Granted, there may be a legit reason that requires a similar action on the part of the User, but until we uncover it, let's try to avoid it for now.

**Comment by paagla123** [comment]
@jiewsone @paweenwich please remember that we discussed about not having to use a "Launch" button in this particular "product". We had discussed that since we have the first one done with the "Launch" button, we will do the second one without (as per Dave's request), and then weigh pros and cons about which is the better approach for long term. Please let me know if this is still the plan.

**Comment by jiewsone** [comment]
I have create all page of this blueprint. We can create/edit campaign, save all steps data to database except step 2 "Set Up Your Landing Page".

**Comment by daver78** [comment]
@paagla123 Shall we close this one and create new Issue(s) for specific items?

**Comment by paagla123** [comment]
@jiewsone I see lots of issues:
1) Section on configure eBook or configure email do not complete saving - the SAVE button just keep circling.
2) Landing pages not set up yet
3) Schedule for second email should be similar to first email - Day/Hours/Minutes off from download.

**Comment by paagla123** [comment]
@jiewsone @coa0329 several problems please.
1) Whether I upload a PDF or choose a link to eBook, the "Configure your ebook" section does not SAVE - cursor just spins and saving is never completed)
2) Schedule for second email should be similar to first - day/hour/minute delay

**Comment by jiewsone** [comment]
I already insert Form Select Box for change the form in Landing page.
But it has known bug, when you select the form, form name in select box not show.
![know_bug](https://user-images.githubusercontent.com/30495168/30211563-bb115bde-94cb-11e7-8d1a-352aef934e72.JPG)

**Comment by paagla123** [comment]
@jiewsone there are multiple issues here:
1) Published campaign cannot be opened in Studio
2) Once we click on Launch button - all of the SAVE buttons start turning again - may be related to above issue. However, remember that the Launch button is not supposed to be on this one.
3) Landing page settings need a lot of love. @daver78 how will the domain be assigned?
4) I do not necessarily agree with the way the pages and the forms are being assigned. @daver78 let us discuss this part before we give it back to @jiewsone

**Comment by coa0329** [comment]
I fixed issue 1.
The variable name in TMAML doesn't match with variable in couchdb.

**Comment by jiewsone** [comment]
When should we change the status of email1 and email2 to Start ?
1 when user click save in step3
2 when user click save in step4
3 other step

**Comment by daver78** [comment]
@paagla123 Did you answer these questions while I was gone?

**Comment by paagla123** [comment]
@daver78 I believe I did - @jiewsone pl confirm
@jiewsone when will we be able to publish this program?

**Comment by paagla123** [comment]
@jiewsone Form spilling out on the right hand side in screen where you create landing pages for eBook #117 created new issue.

**Comment by daver78** [comment]
@paagla123 Let's create a new issue for this in b-web repo; I also have 2 suggestions on how we can handle this.  Let's review those before we request a change?

**Comment by jiewsone** [comment]
@paagla123 Please explain the spec for the "Landing Page settings" tab. 
![image](https://user-images.githubusercontent.com/30495168/30638239-eb05a810-9e24-11e7-83e9-cc030a9eb24a.png)

**Comment by paagla123** [comment]
Guys I will close this monster issue. There are a bunch of open issues on eBook - we will track those and open new ones if needed.
