### ISSUE TITLE
How do we handle two people editing at the same time?

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#35]
@paagla123, I know we briefly discussed this before, but wondering what the latest thinking is re: this scenario:

1- Dave logs into a DV account for MindFire, and clicks campaign "Print 17," then changes some email content.

2- It so happens that at the same time, Kushal is in the same DV account for MindFire, and happens to be editing the same email content in "Print 17".

3- By some magic of the universe, Dave and Kushal both hit "SAVE" around the same time (maybe a few minutes of each other).  

**Questions**:

Who wins in the above scenario?

Should we do anything to protect Users from each other?

**Comment by paweenwich** [comment]
There are also a problem when same user open multiple tab while playing the same campaign.

The person or tab that hit "Save" later (if it need to save the same document) will fail to save because the document's revision number is not sync.

**Comment by daver78** [comment]
@paweenwich OK, what do you think is the solution for your scenario?

**Comment by paagla123** [comment]
We need a semaphore of some sort - don;t we?

**Comment by daver78** [comment]
@paagla123 What is the status of this issue?  Is it a problem?

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#47
