### ISSUE TITLE
Need to mock up a page builder

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#37]
@daver78 can you pl put some thought here? Like banner image at rop, form on right side, body, foooter etc. This will use the Form Asset.

**Comment by daver78** [comment]
@paagla123 Doubtful I will do anything here in the next 2 days.  Shall we push this into next milestone?

**Comment by paagla123** [comment]
@daver78 OK done.

**Comment by paagla123** [comment]
@daver78 please note that I will write up the specs that are in my head here. If I cannot for some reason (e.g. Fogarty's visit) I will discuss when you are back.

**Comment by paagla123** [comment]
Not doing this any more - we've agreed to save pages as we build them.
