### ISSUE TITLE
Sometimes the image in the email for the blog post will got outside of the email area to the left of the screen

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#39]
@paweenwich @coa0329 please see screenshot below.
![image](https://user-images.githubusercontent.com/29718335/29863681-49e13040-8d25-11e7-8873-510ba1a0065b.png). The image shows up in the wrong place if I am not careful about where we drop ot.

**Comment by paweenwich** [comment]
please remove it from print17.  We can not fix it if we can not duplicate the bug.

**Comment by daver78** [comment]
@paagla123 Have you not been able to repro this?

**Comment by paagla123** [comment]
@paweenwich I am adding this back to Print17. Happened to me several times - possibly due to image size and/or internet speed. Let us try this together. It will be quite embarrassing if a prospect runs into it. I had several issues with images today - display related. When I saved it and reopened, worked fine.

**Comment by paagla123** [comment]
Here's the solution discussed and agreed upon:

Instead of allowing users to drag an image over to the email, we will provide a button in the middle of the hero image area. Users will be able to upload an image from their accessible drives using that button. The picture will always render in 100% mode initially - users should be able to change that.

**Comment by jiewsone** [comment]
Please see the Promote a Blog's Email#1 page.
I have insert "Upload image to email" button on this page.
If it's OK, we will add this button to all email.

**Comment by daver78** [comment]
Thank you @jiewsone .  @paagla123 Will test this and confirm.  As for the UI of the button and surrounding area, I will put that on my list and take care of it in the next few days.  

@paagla123 can you create me an Issue for this once you're DONE with the review of this issue?

**Comment by paagla123** [comment]
@jiewsone this is good - please go ahead and roll it out for all emails. Thanks

**Comment by jiewsone** [comment]
I already add the upload button on all email page.

@paagla123  About bug your campaign not show in home page. I already fix it. Please try again.

**Comment by paagla123** [comment]
This is fixed.
