### ISSUE TITLE
Content of Email1 got copied to Email2 & Email3

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#40]
Set up campaign Kushal Blog 10202 under DaVinci account and published. Set up 2 emails with different contents.
Email1: 
![image](https://user-images.githubusercontent.com/29718335/29864522-db6afe72-8d27-11e7-863a-1dd89b4f4f57.png)
Email2: 
![image](https://user-images.githubusercontent.com/29718335/29864547-f15b4ff2-8d27-11e7-98d2-eb8b9e96362e.png)
What we ended up in S3 are two copies of the Email1. Check out:
file:///C:/Users/kusha/AppData/Local/Temp/TEXT-AREA-16916-49ad1da6d9d8f538295d3a4adf80959b-EMAIL1CONTENT.html
file:///C:/Users/kusha/AppData/Local/Temp/TEXT-AREA-16916-49ad1da6d9d8f538295d3a4adf80959b-EMAIL2CONTENT.html

**Comment by paagla123** [comment]
@coa0329 please check email3 also while fixig the bug. Thx

**Comment by paagla123** [comment]
All 3 emails actually have the same content. The email subject lines are different though, just the content is same - all copied from the first email.

**Comment by jiewsone** [comment]
I already fix it.

**Comment by paagla123** [comment]
RESOLVED! Yay!!!
