### ISSUE TITLE
[Promote a Blog Post] Conversion tracking with Google Analytics

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#42]
@paagla123: Where are we with this?  

Who is assigned to this task?

Is it intentionally left off the P17 list?

**Comment by paagla123** [comment]
@daver78 yes. We will deal with this after P17

**Comment by daver78** [comment]
@paagla123 OK, so should we leave it in the UI?  I can see pros & cons to that.

Who is assigned to GA research?

**Comment by paagla123** [comment]
@daver78 I may be confusing things here, but what's the difference between this and the new issue #47?

**Comment by daver78** [comment]
@paagla123 I see 3 discrete things:

1) One issue is making conversion tracking work (with Google, perhaps later with our own web tracking).  As I understand now, we don't intend for this to work before P17, but I'd like to know who will work on it.

2) Another issue is appending a UTM string, which is useful even if we're not doing conversion tracking.  Marketers like their UTM tagging.

3) A third issue is if we are not going to have conversion tracking for "Promote a Blog Post" ready by P17, should we hide that section in the UI.

What say you, good sir?

**Comment by paagla123** [comment]
@daver78 we're addressing issue#47 for P17 - that should cover #2 above. I don;t think we need to hide anything - it will be a good talking point.

**Comment by daver78** [comment]
@paagla123 Wonderful!

**Comment by daver78** [comment]
@paagla123 Where are we with this?  @paweenwich who is assigned to implement this feature?

**Comment by paweenwich** [comment]
@daver78 Sorry, I have no idea what you gays talking about.  I know a bit about GA but not the Conversion tracking.   Could you explain the idea and give me a pointer?

**Comment by daver78** [comment]
@paagla123 I think you covered this with @paweenwich when you were in BKK?

**Comment by paagla123** [comment]
@paweenwich please ready https://blog.adstage.io/2013/11/26/tracking-conversions-with-google-analytics/ to learn about conversion using Google Analytics

**Comment by daver78** [comment]
@paagla123 and @paweenwich, I think neither of you has worked with Google Analytics in this kind of scenario, and thus the concepts seem foreign and complicated.  Let me clarify and try to simplify the mental picture you've created.
----------
Put simply, the question we're answering for the User (in the context of the Promote a Blog Post blueprint) is:

_Of the people who saw my blog post, how many of them went on to complete another action that is important to me?_

Put another way, this could be:

_Of the people who saw my blog post, how many of them went on to buy something from my site?_ or

_Of the people who saw my blog post, how many of them went on to download an eBook?_ or

_Of the people who saw my blog post, how many of them went on to start a free trial?_

This is the question we're answering by allowing the User to mark a conversion point (a page on their website that when reached, signifies an important step in the marketing funnel has been reached).

In order to know if someone has reached that page, we have many ways to accomplish this, but we're going to use Google Analytics for now.

Here's how:

1.  The User's website already has Google Analytics installed.  GA has 55% plus of the web tracking market so there's a good chance the marketer is already using them.

2.  In Step 1 of the Promote a Blog Post, we ask the User to (optionally) specify a page URL that when reached, signifies that the conversion point has been reached.  

3.  Now the User launches their campaign.  People start viewing their blog post.  A percentage of those people go to the next step (make a purchase, start a free trial, download something, whatever it is that's important to the marketer).

4.  On a very regular basis, we query Google Analytics (or configure GA to push data to us), and see who has reached the page the User marked in Step 2 above (the conversion URL).

5.  Now we can show the User their complete funnel: How many people they targeted, how many opened the email, how many clicked to the blog post, and how many took the next important step (whatever it is that's important to the User).

That's it.

At this point, the only question in your mind should be: "_How do we match a visit to the conversion page which we've pulled from GA to a specific person in the Studio DB?_"

Fair question.  

What I suggested to Kushal is that we append something like `contactID=123456` to every link we have in the blueprint leading to the blog post.

Now, when we query GA to see how many people have visited that page, we can look for the `contactID` param, and get the `contactID`to do the match back to the Studio Contact.

Make sense?

Read this carefully and let me know what questions you have about the approach.

**Comment by paagla123** [comment]
@daver78 nice explanation thank you. I think I was on the wrong track. So we don;t need the goals

**Comment by coa0329** [comment]
https://developers.google.com/analytics/devguides/reporting/core/v4/quickstart/web-js

To use Analytics Reporting API. 
1 User must set the permission to use Analytics Reporting API in the account.
2 User give us client ID and view ID.

**Comment by daver78** [comment]
@paweenwich I will answer each of your questions in the same order:

1.  Yes, we should assume the User's site already has GA installed.  Yes, the GA API allows us to access the data.  Yes, we need information from the User in order to do this.

To illustrate this, if you look at [the mockup](https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php?page=myProfileSettings ) and then click on “3rd Party Product Linking” you'll see where we collect the User's `GA Tracking ID`.  However, I think we may need to do an oAuth connection to GA in order to get the data, so the UI may need to expand a little bit in this area.

2.  `UTM` is a URL pattern used by GA and other analytics tools to give the marketer the ability to measure traffic sources.  GA knows how to use UTM to display meaningful data within their reporting.  

I'm not sure what KD showed you about putting GA code in HTML, but that's not required for this portion of the project.  As you stated in 1 (above), we assume the User has GA already installed on their site.

3.  We take the conversion URL that the User has entered, and query GA to see if anyone has reached that page.  If they have, then we know the blog post was responsible for driving the desired action.

@paweenwich when you say  _I don't know how to do with all GA option that we ask user to put in. If you can explain that, we will use xxxx that user input to call API to get yyyy and do zzzzz. This will help a lot._, does what I've written above clarify it for you, or are you asking me to specify which API calls I would make to retrieve the data?  I offered to do that for @paagla123 but he said he would figure it out with you.

@paagla123, I think you need to re-explain this portion in real-time with Kwang.  Perhaps you were on the wrong track last night, and my write-up above has clarified.

**Comment by coa0329** [comment]
I create the mockup to get the report from view "All Web Site Data" in account "StarbucksFirstTaste2017".

Go to http://davincistage.mindfireis.com/admin/HelloAnalyticsReport.html

Click Sign-in button. 
The google Sign-in will popup. 
Enter you google email and password. 
You will ask for permission. 
Click Allow.

You will see nothing , if you cannot access that view ["PERMISSION_DENIED"].
You will see the json of the report in textline, if you can access that view.

![135](https://user-images.githubusercontent.com/7914690/30471880-90faf6da-9a24-11e7-86ae-743ca7cd00b7.JPG)


We need client_id and VIEW_ID from user to access their account.

**Comment by daver78** [comment]
@coa0329 Good progress.  

1.  Regarding the Google Sign button, we should place that in the proper section of Settings as I mention to @paweenwich above ([put it here](https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php?page=myProfileSettings) in “3rd Party Product Linking” )

2.  What are you trying to do with the second mockup which retrieves the Goal Settings?  I believe I told @paagla123 that he was maybe on the wrong track when he spoke to you about that.  I believe he cleaned that up -- or no?

**Comment by coa0329** [comment]
@daver78 

The idea is to get all the goals to use as the option in dropdown for user to select.
We will show the report of that goal using GA api.

**Comment by daver78** [comment]
@coa0329 I think @paagla123 took you on the wrong path during the discussion of this part.  I thought he cleared that up.  @paagla123 Can you discuss tonight before @coa0329 does more work on this part?

**Comment by paagla123** [comment]
@coa0329 No need for Goals. Here's the discussion on Skype last Thursday on this topic:

Here're the API's https://developers.google.com/analytics/devguides/integrate/
Dave wants us to find an API that will retuen all URLs called and then search for a sring in the URL to compute how many people came from our email
So once you find API the rest should be simple

**Comment by coa0329** [comment]
![138](https://user-images.githubusercontent.com/7914690/30574367-a1558732-9d23-11e7-911c-1c44c1bf025a.JPG)


Do you mean we use GA api to get page visit then match it with Conversion URL user setting in each campaign ?

**Comment by paagla123** [comment]
@coa0329 That is correct. The conversion URL will have a particular string that we put there and search for it from the result of GA API calls.

**Comment by coa0329** [comment]
Goto http://davincistage.mindfireis.com/admin/HelloAnalyticsReport.html

![141](https://user-images.githubusercontent.com/7914690/30579457-f9f36b1a-9d42-11e7-8232-0d4cda270b78.JPG)


I modify the code to get the pages from GA api.

So now we can use them to match with Conversion URL user setting, then create report.

**Comment by coa0329** [comment]
We will add the following parameters "campaignID={{campaignID}}&contactID=##id##&source=EMAILX" to the call to action link in all emails so we will have the information from GA.

This is the example link in email

http://davincistage.mindfireis.com/admin/GA_test2.php?campaignID=a45f6961a4d7f7783f9232b7dc9de381&contactID=1&source=EMAIL1&utm_medium=email&utm_source=Blog&utm_campaign=My+Blog&utm_term=Write

**Comment by daver78** [comment]
@coa0329 Good thinking on passing the email `source=EMAILX`.  Thanks for considering that important angle.  @paagla123 I assume you can see the validity of this param.

What's the next step?

**Comment by coa0329** [comment]
Working on it.

**Comment by paagla123** [comment]
@coa0329 remember to save the information about the person that converted somewhere in the cDB. Also reminder to use contactID and not anything that is identifiable with the person.

**Comment by paagla123** [comment]
@coa0329 I have set up a campaign with conversion points for your to test. Its called Blog-0925-Google Analytics-Test .

**Comment by coa0329** [comment]
@paagla123 

cDB cannot do that, If you want to keep the person information we need to use mysql db.

We must create the daily cron to get data from GA to save in our db.

**Comment by paagla123** [comment]
@coa0329 permission given. Why do you say cDB cannot do it?

**Comment by paagla123** [comment]
This issue was moved to coa0329/BhaangWeb#65
