### ISSUE TITLE
[Promote a Blog Post] Email "View Online" feature

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#43]
@paagla123 Where are we with this?  And what is your plan relative to P17?

**Comment by paagla123** [comment]
Looks like we got too excited and missed this one!
@paweenwich we should address this please. Thx

**Comment by daver78** [comment]
@paagla123 How are you going to handle the "gymnastics" (that is, the link shows up in the email version, but not in microsite page version)?

**Comment by paagla123** [comment]
@daver78 pl review for position and font size. The link is not working yet - I am happy to leave it this way for P17. The link will require us to work out the domain issue which I will open a new issue for.

**Comment by coa0329** [comment]
We add View Online Message, Company Name, Company Address and Company Phone in Settings.

They will be rendered in all email content.

![095](https://user-images.githubusercontent.com/7914690/29920632-777c7ec0-8e78-11e7-9c21-1588bb9e8b8d.JPG)

**Comment by daver78** [comment]
@paagla123 and @coa0329 I will check it out.

@paagla123 In addition to the domain issue you mention, you also have to figure out how to remove the "View online message" from the microsite page, right?

**Comment by paagla123** [comment]
@daver78 we will need to figure that out eventually. I am going to close this issue for now. I will open a new one for the domain issue.
