### ISSUE TITLE
[Promote a Blog Post] Replacing company vars in the email(s)

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#44]
@paagla123 Are we ingesting the global company vars from "Settings" and placing them in the "company email" template?

If not, what is the plan relative to P17?

**Comment by paagla123** [comment]
@daver78 Email does not have company vars any more - ts in the template. The Vars in the template should get linked to the company name etc input during registration. DO you want to address it before P17?

**Comment by daver78** [comment]
@paagla123 I would like to, yes.

**Comment by coa0329** [comment]
We add View Company Name, Company Address and Company Phone in Settings.

They will be rendered in all email content.

![095](https://user-images.githubusercontent.com/7914690/29921898-a5d2a9ac-8e7d-11e7-85d5-6c5b5b7e7380.JPG)

**Comment by paagla123** [comment]
So this is working - I will close this issue
