### ISSUE TITLE
[Promote a Blog Post] After a schedule has passed, should no longer be editable?

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#45]
@paagla123 Once the date/time has passed for the initial blast, that schedule should no longer be editable. 

True, false?

**Comment by paagla123** [comment]
@daver78 should be true.
@paweenwich it does not work that way. Can we please fix? Thx

**Comment by daver78** [comment]
@paagla123 Is this still open?

**Comment by coa0329** [comment]
![150](https://user-images.githubusercontent.com/7914690/30737484-0646a402-9fb1-11e7-9bd3-2e319bf99f4e.JPG)

When the schedule has passed.

1 We will disable the input. 
2 We will hide clock and calendar button. We will try to disable them later.

**Comment by daver78** [comment]
@paagla123 there is an important thought here that I've held back discussing because I'm waiting for you to run a real-life campaign and raise it on your own (therefore, validating whether or not it is really an issue), but we should probably discuss in the event that you feel we should it address it.

Let's discuss this one today.
