### ISSUE TITLE
Create small website or landing page at dv.mindfireinc.com

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#46]
Create a small website:
- promoting the benefits of DV
- providing a "sign up now" link
- providing a "login in" link

Will be used at Print17 and ongoingly as we develop messaging for the product.

@paagla123, this is why I need to be able to place an `index.htm`l at `dv.mindfireinc.com`.

**Comment by paagla123** [comment]
@daver78 OK
@paweenwich or @coa0329  Can you pl help me go through this and explain to Chay?

**Comment by paagla123** [comment]
@daver78 just create teh website and provide the URL to @paweenwich . He will put the index.html at the appropriate place

**Comment by daver78** [comment]
@paagla123 Sorry I don't get your comment.  What do you mean "provide the URL to @paweenwich"?

- Do you want me to get the site up and running at S3? or

- Do you mean provide @paweenwich  the `HTML` (URL is typo)?

Sorry not trying to be silly just making sure I understand you.

**Comment by daver78** [comment]
@paweenwich See above what @paagla123.  Before I configure S3 to house the site (`index.html`), which is what @paagla123 told me to do this morning, I want to verify with you that this is what you meant.

Can you confirm?

S3 would be great, as it opens up a lot of power for us.  Let me know if I should proceed.

**Comment by daver78** [comment]
@paagla123 Here is the draft: `https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/DV-website/index.html`

@Mcfarsheed and @paagla123 this is mostly placeholder text.  That needs a lot of thought.  But overall direction is here.

**Comment by paweenwich** [comment]
@daver78  Right now  dv.mindfireinc.com  point to web2xmm.com (the machine that we are working on).  We can provide the user/password (if you don't have one), so you can create index.html and doing thing yourself.  Or (as I told KD),  you can give us the URL to your site (can be S# or what ever) and I will create index.html which will redirect to that URL.

**Comment by daver78** [comment]
@paweenwich Here is the website endpoint where we will host the site: http://mindfiredavinci.s3-website-us-east-1.amazonaws.com/

I think your idea of redirecting to this URL is OK for now, but it is possible to point a domain to S3 directly: http://docs.aws.amazon.com/AmazonS3/latest/dev/website-hosting-custom-domain-walkthrough.html (take a read when you have a moment).

If you're curious, I sync the HTML from my C9 machine (which is synced with Git) using the AWS CLI.  This is the command: `aws s3 sync . s3://mindfiredavinci`

Makes it very simple.

**Comment by paweenwich** [comment]
@daver78  index.html now redirect to  http://mindfiredavinci.s3-website-us-east-1.amazonaws.com/
So, https://web2xmm.com/ will redirect to the microsite site.

**Comment by daver78** [comment]
@paweenwich Thank you.

@paagla123 and @Mcfarsheed, I've intentionally kept the site simple to limit the amount of work we need to do -- but we should be intentional about our messaging.  I'll close this issue for now and open another one for messaging on the website.
