### ISSUE TITLE
Provide for UTM code string in the link URL to the Blog Post

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#47]
Be aware that at some point soon, we will also need to:

a) Append a UTM string to the <a href>.

(I'm not sure where the team is relative to getting Google Analytics figured out in order to track conversions, but I believe the UTM string is going to play a part in this.)

b) In future, we may need to pass additional vars in query string format.

I raise this so that you consider it when you code it. Give yourself room for this.

**Comment by daver78** [comment]
@paagla123 I'm not sure how much you've worked with UTM for yourself or Clients, but there are a few basic needs:

1- We should use UTM by default to make it easy for folks to measure campaigns in Google or any other analytics package that abides by the UTM standards.  

2- Some folks will want to modify the UTM string to fit into their own tracking philosophy (just like you can in Facebook Ads).

Here's an example of a string we might create and append:

`utm_source=DaVinci&utm_medium=Email&utm_content=Email1&utm_campaign=Print17`

**Comment by paagla123** [comment]
@daver78 I understand

**Comment by paagla123** [comment]
We will add this for Print17. Facebook ad style. There will be a field to fill in tracking code, which could be UTM string or Studio's Source tracking etc

**Comment by paagla123** [comment]
@daver78 this has been added - please check.

**Comment by paagla123** [comment]
Can we test with our own UTMs for our blogs please?

**Comment by paagla123** [comment]
I already tested, the utm string is getting passed https://www.forbes.com/2009/12/23/asia-exotic-foods-lifestyle-food-wine-holiday.html?utm_source=dv&utm_campaign=q123ssd . We ca close this after we test with MindFire blog

**Comment by coa0329** [comment]
We add the UTM string for user to enter in step1.
We will append it to the url then put it in the link in email content.

![094](https://user-images.githubusercontent.com/7914690/29920548-20278f3e-8e78-11e7-83f3-5be97d280989.JPG)

**Comment by daver78** [comment]
@coa0329 Not bad!  I may want to give it some love (small love) but great start!

**Comment by paagla123** [comment]
Closing it for now.
