### ISSUE TITLE
Create a MAML for eBook

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#48]

**Comment by daver78** [comment]
@paagla123 You OK doing this?  I think you know what needs to be done based on the articulate Blueprint Steps.  Yes?

**Comment by paagla123** [comment]
@daver78 ok

**Comment by paagla123** [comment]
@paweenwich @coa0329 I have checked in the first version. Let us review in the morning and then we can hand off to @AumpaiFung

**Comment by paagla123** [comment]
Created: eBookPromo_MAML-v2 @coa0329  @AumpaiFung  please use this MAML.
