### ISSUE TITLE
Using Github issues.

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#5]
We should replace feature_backlog.txt with github issues.

It will be easier to keep tracks the issue.

**Comment by jiewsone** [comment]
Jiew test.

**Comment by AumpaiFung** [comment]
number five

**Comment by daver78** [comment]
Makes sense to me too.  @paagla123 I will leave you commentary and notes between us in the .txt file.  We can use 'issues' for actual to-do items.

**Comment by daver78** [comment]
I think we all agree on this one so I will close.  Thank you for the suggestion, Coa.
