### ISSUE TITLE
Next milestone date established

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#50]
@paagla123 The next opportunity we have to engage prospects and customer at an event is MarTech in Boston, and thINK in Florida.  They're both the first week of October.

I set the next milestone date based on the earliest of the two, which is MarTech.

Once you have a handle on the P17 stuff, let's start assigning things to this milestone.  Does that makes sense to you?

**Comment by paagla123** [comment]
@daver78 ok

**Comment by daver78** [comment]
Closing.
