### ISSUE TITLE
[Promote a Blog Post] Change MAML Campaign Name to "Promote a Blog Post"

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#51]
Currently, MAML seems to have hard coded campaign name `Beneficiary Business`.

Please change to `Da Vinci: Promote a Blog Post`

**Comment by paagla123** [comment]
Done. Also changed the word Click to Open in one place in the Open trigger email. Saved as v10 - @coa0329 please use this version moving forward - thank you.
