### ISSUE TITLE
Change Page Title from Main Template to daVinci - Digital Marketing Guru

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#52]
@daver78 Do you approve of this title or something else. We cannot have it called Main Template as we go into P17.

**Comment by daver78** [comment]
@paagla123 Hmmm, which page are you talking about?  Or, are you talking about the `<title>` tag that is on all pages?

**Comment by paweenwich** [comment]
@daver78 Yes, the <title> in all pages right now are "Main Template".  We just keep copying from your original mock up and did not have a change to change it.  :)

**Comment by paagla123** [comment]
FIXED Closing
