### ISSUE TITLE
Create Internal Domains for Blog Emails

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#53]
This domain will be used to host the online version of the emails as well as the unsubscribe landing page. Not required for P17, but we cannot go to production without this.

**Comment by daver78** [comment]
@paagla123 What are you asking me to do?  I'm OK with whatever generic domain we come up with.

**Comment by coa0329** [comment]
@paagla123 @daver78 @paweenwich 

We don't need the site for online version. We can save them on S3.

The current process, we will render the email, save it as html and upload it to S3 when user click save email.

We can save 2 html each time user click save  when user click save.
1 The html without view online in the content for view online. (We can use the same file name with suffix like _online in the filename)
2 The html with view online in the content. Then we put the link of #1 in it. 

Example.
For email1 of campaignid a3fbe4d26d00539cc0200035408a5377
1 We save the html without view online to https://s3-us-west-1.amazonaws.com/bkktest/tmp/TEXT-AREA-16916-a3fbe4d26d00539cc0200035408a5377-EMAIL1CONTENT_online.html
2 We add the link of #1 to view online link in the content then we save the html with email to https://s3-us-west-1.amazonaws.com/bkktest/tmp/TEXT-AREA-16916-a3fbe4d26d00539cc0200035408a5377-EMAIL1CONTENT.html

**Comment by daver78** [comment]
@coa0329 You can't use this technique because `https://s3-us-west-1.amazonaws.com/bkktest/tmp/TEXT-AREA-16916-a3fbe4d26d00539cc0200035408a5377-EMAIL1CONTENT.html` will not personalize variables like `##firstname##`.

This is why the Microsite is useful; we can use the HTML we've saved to S3 inside a Microsite page, which gains us personalization.

Does that make sense?

**Comment by coa0329** [comment]
ok. I got it.

**Comment by coa0329** [comment]
We save 2 versions of the html on S3. (with and without view online link)

We create the mircosite in the maml. We set the domain to davinci.m.mdl.io.
When user launch the program
1 We will automatically add sub domain to the microsite using _id from davinci. Example 583deefb2ba32388e98a4d82b4740faa

2 We will add the ##purl##, domain and emailX.html in the link in email content. Example http://##purl##.davinci.m.mdl.io/583deefb2ba32388e98a4d82b4740faa/EmailX.html

In each html in microsite we put the new set of variables ##emailXcontentonline## in EmailX.html. It will convert to the link on S3 for user to see the html without view online.

**Comment by daver78** [comment]
@paagla123 Will you verify this?

**Comment by paagla123** [comment]
I will test

**Comment by coa0329** [comment]
@paagla123 @daver78 Please Verify, Are you ok with this solution ?

**Comment by coa0329** [comment]
We cannot use the same domain for both account. We must add the account id to it.
The domain for campaignlauncher will be davinci228.m.mdl.io
The domain for davin ci will be davinci16916.m.mdl.io

**Comment by daver78** [comment]
@coa0329 This makes sense to me.  @paagla123 Do you agree?

**Comment by daver78** [comment]
@coa is this still open?

**Comment by coa0329** [comment]
@paagla123 said this will not include in Print17.

**Comment by daver78** [comment]
@paagla123 Was that intentional?  I see you moved it to MarTech milestone.

**Comment by coa0329** [comment]
@paweenwich 

We save 2 versions of the html on S3. (with and without view online link)

We create the mircosite in the maml. We set the domain to davinci.m.mdl.io.
When user launch the program
1 We will automatically add sub domain to the microsite using _id from davinci. 

2 We will add the ##purl##, domain and emailX.html in the link in email content. Example http://##purl##.davinci{{acctID}}.m.mdl.io/{{progID}}/EmailX.html

In each html in microsite we put the new set of variables ##emailXcontentonline## in EmailX.html. It will convert to the link on S3 for user to see the html without view online.

**Comment by coa0329** [comment]
This issue was moved to coa0329/BhaangWeb#24
