### ISSUE TITLE
Self-sign up and Registration of users

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#55]
We will need a long term strategy of how to do this. It may go to the website Dave is creating. We need to start contributing to this. I suggest we start a Wiki on this topic and contribute.

**Comment by daver78** [comment]
In the mini-website I'm creating there is a place to sign-up.  For now, I'm jeeping the site minimal so that we have enough for P17.

@paagla123 do we have the php for creating new users yet?  If not maybe we need an issue for that -- or is that what this is for?

**Comment by paagla123** [comment]
Superseded by issue#60 - closed
