### ISSUE TITLE
Template for trigger.

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#56]
We will get the content of the trigger from S3. So Kushal can change it without changing the TMAML.

For Promoteblog
OpenAlertLeadTrigger :
https://s3-us-west-1.amazonaws.com/bkktest/template/promoteblog_clickalert.html
ClickAlertLeadTrigger :
https://s3-us-west-1.amazonaws.com/bkktest/template/promoteblog_openalert.html

For Ebook
OpenAlertLeadTrigger :
https://s3-us-west-1.amazonaws.com/bkktest/template/ebook_clickalert.html
ClickAlertLeadTrigger :
https://s3-us-west-1.amazonaws.com/bkktest/template/ebook_openalert.html

---------

Please pull the latest TMAML v 10 from git.

**Comment by paagla123** [comment]
This is done for eBook as well. @coa0329  please use eBookPromo_MAML-v2 moving forward.
