### ISSUE TITLE
Call to Action Button in Blog Email

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#58]
The text on the CTA button cannot be changed as it goes to the link to the blog when clicked. To resolve this, the href will be saved only during publish or send test.

**Comment by paweenwich** [comment]
Done.  (When edit I either remove href or change <a> to <aview> (tag that browser does not care)

**Comment by daver78** [comment]
@paagla123 Will you test and confirm?

**Comment by paagla123** [comment]
I will test.

**Comment by paagla123** [comment]
FIXED Closing
