### ISSUE TITLE
Development Environment

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#59]
Currently the code is being kept on the server @ Digital River and is being backed up to github nightly. It is recommended that we use github for development and that individual deveopers use Cloud9 for their development and test environment (c9.io), @paweenwich to answer your question on where individual develper's database should be, we can get database containers from Docker - pl check out https://www.docker.com/what-docker .

**Comment by daver78** [comment]
@paagla123 and @paweenwich Oops, I didn't see this issue.  I created #74 for Docker.
