### ISSUE TITLE
Step 3 : Wait Logic

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#6]
- Step 3
What is the logic for wait ?
Example 
Email 1 send on 08/01/2017.
Email 2 wait 2 days.
Email 3 wait 3 days.

Case 1 :
Email 2 : We will add 2 days to 08/01/2017 = 08/03/2017.
Email 3 : We will add 3 days to 08/01/2017 = 08/04/2017.

or 

Case 2 :
Email 2 : We will add 2 days to 08/01/2017 = 08/03/2017.
Email 3 : We will add 3 days to 08/03/2017 = 08/06/2017.

**Comment by daver78** [comment]
Case 2 is how I envisioned it.  We may need to adjust the wording in the UI
but let's proceed with case 2 logic.

-dr-

*PS*:  *Are you an auditory learner?  Weekly, we bring you the latest
strategies for using multi-channel marketing automation to boost leads &
sales <http://bit.ly/PixelsAndInk>.  From the industry's top sales &
marketing minds, you’ll hear what’s working -- and not working -- so you
can be on the cutting edge without having to empty your wallet in the
process.*

<http://bit.ly/PixelsAndInk>

David Rosendahl
Co-founder

Online: https://www1.gotomeeting.com/join/767901648; Dial 1-630-869-1016
and enter: 767-901-648
Cell: 949.375.4459
Ofc: 949.474.4418 x208
*
--------------------------------------------------------------------------*

**Comment by coa0329** [comment]
We will proceed with case 2 logic.
