### ISSUE TITLE
No HREF in the CTA link in the PLAIN EMAIL (one without image)

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#63]

**Comment by paweenwich** [comment]
Done, (add href and view online)

**Comment by daver78** [comment]
@paagla123 Will you test this and confirm it is OK per your wishes?

**Comment by paagla123** [comment]
I will test.
@paweenwich have you addressed the issue as in #58 (When edit I either remove href or change to (tag that browser does not care)?

**Comment by paagla123** [comment]
FIXED - Closing.
