### ISSUE TITLE
Questions for ebook.

### ISSUE THREAD

**Issue by coa0329** [coa0329/Bhaang#65]
1 Schedule

How to set schedule for ebook ?

![103](https://user-images.githubusercontent.com/7914690/30023869-7f94beb2-919b-11e7-9938-aa30ce243360.JPG)

![102](https://user-images.githubusercontent.com/7914690/30023884-8d2163f0-919b-11e7-85d3-a65d77b02b9e.JPG)

For email1 we can set the number of days, hours or minutes user enter.

For email2 we can set the number of days. But how can we set hours and minutes ? 
Should we change the time to hours and minutes ?

-----------------

2 Template 

Please put the templates for the Landing page and thank you page to git.

**Comment by paagla123** [comment]
@coa0329 I suggest we allow users to enter day, hour, minute for all emails. I also suggest that please change the schedule for the microsite in the MAML template and extend it to end in 2050. Thanks

**Comment by coa0329** [comment]
@paagla123 I extend the rime to 2050

**Comment by paagla123** [comment]
I am closing it - same issue described in #34
