### ISSUE TITLE
Where is the Template and config files for Blueprint Promote an eBook?

### ISSUE THREAD

**Issue by jiewsone** [coa0329/Bhaang#66]
Where are the Landing page and thank you page themplate files and the config files(Default Text)?

**Comment by paagla123** [comment]
@jiewsone its in GitHub\Bhaang\httpdoc\daver\Blueprints\Promote-an-eBook. I will add the Thank You page as well.

**Comment by paagla123** [comment]
@daver78 what is your vision on what happens when someone clicks on the email button? Is that just a mailto link with a link to the eBook? Remember, we still need to work on teh domain part.
