### ISSUE TITLE
Promote an eBook Product Image

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#68]
It is using the wrong image - same as Email Blog. Should be:
![image](https://user-images.githubusercontent.com/29718335/30035773-5e3b5750-9162-11e7-9fac-803387713094.png

@jiewsone please get it from https://da-vinci-rules-daver78.c9users.io/httpdoc/daver/dv.php?page=pickAnObjective . Thanks

**Comment by paweenwich** [comment]
@paagla123  I think Dave fixed this one.  Now, 
My Campaign show    "kwang1 (Promote a Blog Post)  Modified 15 hours ago "
Home page show "kwang1 (Promote a Blog Post) Modified 15 hours ago"

Or you mean something else?

**Comment by jiewsone** [comment]
From #64 , I guess Dave have upload incorrect image to S3.
Here is the Promote an eBook image src in code "https://s3.amazonaws.com/mindfiredavinci/img/ebook_blueprint.jpg".

Could you or Dave please upload the correct image to S3?
Because I cannot see mindfiredavinci bucket on S3.

**Comment by jiewsone** [comment]
The Promote a Blog's image src still not use S3.
Here is the current image src in code
"<img src="http://www.solostream.com/wp-content/uploads/2016/08/wordpress-custom-post-types.jpg" class="img-responsive" />"

Please upload the image and send me the S3 link, I will change the code.

**Comment by coa0329** [comment]
Please grant the permission for us to access mindfiredavinci bucket.

sithiporn@mindfireinc.com
boonsom@mindfireis.com
aumpai@mindfiremail.info

**Comment by paagla123** [comment]
Here's the link to the correct image. You can download it from this location and upload to S3.
https://cdn.elegantthemes.com/blog/wp-content/uploads/2016/01/WordPress-eBooks-FT-shutterstock_298676606-adichrisworo.png

**Comment by coa0329** [comment]
Fixed

**Comment by daver78** [comment]
@paagla123 This was my bad.  I see the fix that @coa0329 did and I updated it to point to the same location on S3 that the other images are at.
