### ISSUE TITLE
editpromoteblog.php: the font has changed and the text wraps

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#69]
Please see detailed notes on issue#67

**Comment by paweenwich** [comment]
@paagla123 I think Dave also fixed this one.

**Comment by paagla123** [comment]
Fixed closing

**Comment by daver78** [comment]
@paagla123 and @paweenwich  We need to apply the same treatment to "Promote an eBook".  Who should this be assigned to?
