### ISSUE TITLE
html code shows up in the emails delivered using PLAIN template

### ISSUE THREAD

**Issue by paagla123** [coa0329/Bhaang#71]
First of all, this problem exists only in emails SENT by Studio after Launch. SEND TEST emails for not have this problem.  Basically, the email shows up with html tags. Example below:
![image](https://user-images.githubusercontent.com/29718335/30037454-c0ff16c6-916f-11e7-93eb-7d280e3ddf9e.png)

**Comment by coa0329** [comment]
Fixed.

**Comment by paagla123** [comment]
Fixed closed
