### ISSUE TITLE
Consider "dockerizing" Da Vinci

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#74]
See [https://www.docker.com/what-docker](https://www.docker.com/what-docker) and related documentation.  I believe we should institute this fairly soon.  Can you read it and see what you think?

**Comment by paweenwich** [comment]
I am asked Chay to help us to Docker the Davinci.   He is working on that.   Right now, it is on the same state as codeanywhere  (working on configure the /couchdb to point to remote database).

**Comment by daver78** [comment]
@paweenwich Do you want to invite him to participate in the discussion here?  I think @coa0329 can add him.

However, when you say the current issue is pointing to the remote database, that shouldn't be a problem if you include the database within the docker container.

In other words, when our developers get the container and run it on their dev machines, it should contain *everything* they need, including the database.

Do you see what I'm saying?

**Comment by paweenwich** [comment]
@daver78 I see your point.   Yes, isolation always better.   However, this is first time we just play with the Docker.  And just learn that it differs from VMware.   So, less configuration is easier.   I think we can live with shared database for a while.   Right now, we have solved the database problem and working on a new problem (missing php module).

**Comment by daver78** [comment]
@paweenwich Yes, it is very powerful, and is different than VM.  For example, with Studio, we have dockerized portions which means that any developer can get the subsystem up and running on their computer without delay -- regardless of their machine type (PC, Mac) and OS.  It's *beautiful*.

That said, I agree we can live with the shared database right now.  Will you still have Chay look into Docker, and thus we should leave this issue open?

**Comment by paweenwich** [comment]
Yes, leave this open until we have DV's docker.  Codeanywhere is good but ultimately, Docker seems just better in term of reliability and performance.

**Comment by daver78** [comment]
@paweenwich Agreed!

**Comment by paagla123** [comment]
@daver78 @paweenwich this also should be closable now - right?

**Comment by paagla123** [comment]
@daver78 @paweenwich we should be able to close this now - right? We've moved n a different diection.

**Comment by daver78** [comment]
@paweenwich What is the different direction?  I missed the discussion.

**Comment by paweenwich** [comment]
@daver78 Sorry, Dave.   We have last week, we move to codeanywhere first while Chay try to Dock davinci.  With in a few day, we experience "proxy error" from the codeanywhere server after using it for a while.  It seems like, the server is limited CPU usage and cause a lot of timeout.   We end up setting up VirtualBox (ubautu14 )  for everyone instead which easier for us to do than docker.   

Right now everyone has his/her own Davinci Virtual box.   This give us better performance than codeanywhere.

**Comment by daver78** [comment]
@paweenwich No problem.  Should I also work with a virtual box, or shall I continue using codeanywhere?

**Comment by paweenwich** [comment]
@daver78 Codeanywhere give us a lot of trouble.  (May be due to our internet connection).   You can stay with codeanywhere if it work fine for you.  However, we can give you the Davinci's virtual box image that we set up if you like.

**Comment by daver78** [comment]
@paweenwich I will continue using codeanywhere for now, but sure, send me the DV VB image so I can take a look.

By the way, when using Docker, were you trying to run it on codeanywhere, or your local machines?
