### ISSUE TITLE
[Promote a Blog Post] Give love to the "Company Email" Template

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#77]

**Comment by daver78** [comment]
Updates made today:

- @paweenwich Can you please replace `COMPANY-EMAIL.html` with `COMPANY-EMAIL-D1.html `?  I can easily do it but thought you may want to?

- @paweenwich Where do I set the “View online Message” default content?  When does that get set?  I would like it to be: 
`"defViewOnline": "Email not displaying correctly? View it in your browser."`

- Centered hero image, made default hero image, and inserted into template: `https://s3.amazonaws.com/mindfiredavinci/img/DV_image_placeholder_600x300.png` 

- Removed MindFire logo and put in: h`ttps://s3.amazonaws.com/mindfiredavinci/img/DV_image_placeholder_180x70.png` … but as @paagla123 correctly noted, we need to allow user to set this globally and `<a href> `it to their company website.  @paagla123 will you create an Issue for this?

- @paagla123 Before I've published my Campaign, and I work on my email and do a "Send Test", I receive the email but the "View online" link does not work.  I thought you addressed this somehow?

**Comment by daver78** [comment]
@paweenwich I notice that PLAIN email has `href="[[REMOVE {{RAW URL-BLOG-POST-URL}}?{{RAW URL-BLOG-POST-UTM}}]]"` while COMPANY is missing `{{RAW URL-BLOG-POST-UTM}}`

Is this an oversight, or intentional?

**Comment by daver78** [comment]
@paweenwich and @paagla123, there are two open questions for you above (View online message for Kwang, and "Send Test" for Kushal).

**Comment by paagla123** [comment]
@daver78 issue#100 opened for logo.
@paweenwich can you please respond to your questions and close this issue?

**Comment by paagla123** [comment]
@daver78 View Online will be done now as part of Martech release

**Comment by paweenwich** [comment]
@daver78 no Default can be set right now for dfViewOnline.  We will implement it.  However, in a mean time, we can code it in accountSetting.php

**Comment by coa0329** [comment]
@daver78 You can set it in setting.

![125](https://user-images.githubusercontent.com/7914690/30314705-c17ac66a-97cb-11e7-98c3-ec23c6ffb938.JPG)

**Comment by paweenwich** [comment]
Coa is right.  My fault :).

**Comment by daver78** [comment]
@paweenwich Yes, I know you can change it in "Settings" but I want the system default to match what I've written.  Can we make that happen?

**Comment by paweenwich** [comment]
@daver78 yes.

**Comment by daver78** [comment]
@paweenwich OK.  Do you want another issue for this?  If so, please close this one and create one specific for that?

**Comment by paagla123** [comment]
@daver78 @paweenwich what is the conclusion here?

**Comment by paweenwich** [comment]
Please use this issue, will update here when the default_useinfo is done.

**Comment by daver78** [comment]
@paweenwich OK.  We will await your update.
