### ISSUE TITLE
Where can I edit the Emails and Landing Page (Welcome, Thank-you) Templates? 

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#80]
@paweenwich I haven't searched, so would you kindly advise the location of the templates (or the various locations if they're in different places)?

I will want to make some updates to them over the next 2 days.

**Comment by paweenwich** [comment]
@daver78 /admin/templates contains all the templates that will be used.  For example, emails contains emails templates.  Right now, we have only 2 of them, "COMPANY-EMAIL.html" and "PLAIN-EMAIL".html.  The json in DB at /master/templates contain necessary information  about blueprint and templates that available.  

  "blueprints": [
       {
           "campaignType": "eNewsLetters",
           "template": "EmailMarketing_NO_LandingPage.TMAML-v2.maml"
       },
       {
           "campaignType": "PromoteBlog",
           "template": "EmailMarketing_NO_LandingPage.TMAML-v10.maml"
       },
       {
           "campaignType": "PromoteEbook",
           "template": "eBookPromo_MAML-v2.maml"
       }
   ],
   "emails": [
       {
           "title": "Company Email",
           "file": "COMPANY-EMAIL.html",
           "default": ""
       },
       {
           "title": "Plain Email",
           "file": "PLAIN-EMAIL.html",
           "default": ""
       }
   ]

The "pages" is not using right now.   

BTW, I need to explain about the syntax in the pages  (EMAIL).  They are quit complex that I am confusing myself sometime.  

[[REMOVE  XXXXX]]     
The XXXXX will be remove when showing in Davinci.   When render for MAML, it will retain XXXXX.

{{XXXXX}}*
Will HTML encode and render value of XXXXX field in current document.  

{{RAW XXXXX}}*
Will direct render (no encode) value of XXXX field in current document.

*For field start with EMAIL# it will be automatically render in to summernote tag in only in Davinci.

I think the bestway to play around is to add more email templates and you play with those new templates.   I can add more template file in DB for you, so you just edit those new files.

**Comment by daver78** [comment]
@paweenwich I will study your notes re: the syntax in the emails tomorrow.

If you think it is better for me to work on the emails is by adding templates instead of editing the two existing, then please proceed with a copy of both the PLAIN and COMPANY.  I'll make those look the way we want and then we can eliminate the first two copies.

Is that OK for you?

**Comment by paweenwich** [comment]
Yes.  I create 4 templates for you, COMPANY-EMAIL-D#.html, PLAIN-EMAIL-D#.html.   It already shows up in UI.  So, you can modify the those templates as you like.    Release remember, we load add template once when the page (editBlocgpost.php)  load.  So, you need to refresh the page to get the new content you update.

**Comment by daver78** [comment]
@paweenwich Thank you.  Will do and close this issue.
