### ISSUE TITLE
Make Dave's codeanywhere DV development platform work

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#81]
@daver78 Let discuss the topic here :)

**Comment by daver78** [comment]
@paweenwich Excellent.  Here and ready to help! :)

**Comment by paweenwich** [comment]
I can not access codeanywhere.com all day long (Page can not display).  I can get the login screen, but when try to open Edit to it fail.  Will try again tomorrow.

**Comment by daver78** [comment]
@paweenwich Hmmm, that's odd.  Let me know what happens when you try again.

I also believe you can get the docker container for their app and run it locally.  I know you can do that for c9.io if I'm not mistaken.

**Comment by paweenwich** [comment]
@daver78 I can access today.   I think yesterday, something wrong with their service.   Anyway, right now Davinci in codeanyway is working (I  tested a  couple pages).     Here are what I did. 

1) dave.conf
-correct DocumentRoot "/home/cabox/workspace/html"
-correct typing error on ProxyReverse 

2) disabled the 000-default.  

3) change php reporting for apache2 (/etc/php5/apache2/php.ini) from 
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT
to
error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE

This prevent notices to throw out and interfere with the output.  

I think you can try the Git pull/push to sync code with us.   We will pull all the code from GIT at 9.00 and push all the code at 18.00 (Thai time).   Let's try this way for a while.  :)

**Comment by daver78** [comment]
@paweenwich Excellent.  I will try codeanywhere either tonight or early tomorrow and let you know how it goes.

But in terms of pushing at certain times, do we need to do that?  Here's what I'm thinking:

1- If every developer (including me) is checking out the latest code at the start of their day, and then checks in as they complete work or at the end of their day, GIT should remain updated.

2- You (or someone you assign) can then be responsible for going to the web2xmm server and pull from GIT when we have a new stable update.  

(However, it is likely that soon we will want to pull the latest to a staging environment first, run tests, make fixes if necessary, and then pull the stable release to web2xmm.)

Do you agree with this process?

**Comment by paweenwich** [comment]
Git thing is new to me.  So, I am worry about code merging.  We (Thai developer) tend to edit the same file all the time.  I just afraid that we might lost some works during code merging.   

Anyway, we agree with your suggestion.

**Comment by daver78** [comment]
@paweenwich regarding code merging, this is what GIT is great at doing.  

There are documentation/tutorial on GIT site that you can read about how it works.  

Another way to experience it is do a simple test: You pull the repo, edit `test.php`.  Have Coa pull the repo, and also edit `test.php`.  Both of you commit your changes, and push.  You'll see how it handles the merge.

We can also use pull requests, which you'll see in the documentation/tutorials.

**Comment by daver78** [comment]
@paweenwich and @paagla123, regarding the question posed in last night's chat:

![image](https://user-images.githubusercontent.com/7561473/30172437-acc7a98e-93a9-11e7-8d09-eb44b65346de.png)

Yes, you can use my credentials to codeanywhere, but I suggest something different: Each person who is going to contribute this project should create their own account.  You can see the very competitive pricing below (I'm currently on the free plan, have never had to upgrade ... but if necessary, it's very cost-effective).

If everyone has their own creds, then each person can `pull` from github to their codeanywhere and commit updates as they work.  Kwang can then update the staging environment daily (eventually, if all tests pass, we can automate that too).  

I know that Kwang is still figure out how to use git in the multi-user environment, so next week is probably a good time to study that and get everything prepared while we are at the show.

![image](https://user-images.githubusercontent.com/7561473/30172480-cc591166-93a9-11e7-91a3-2885bfda392a.png)

**Comment by daver78** [comment]
@paweenwich and @paagla123 This seems to be working!  The code is running on my dev machine at this URL: [http://da-vinci-core-daver438618.codeanyapp.com/admin/](http://da-vinci-core-daver438618.codeanyapp.com/admin/)

**Comment by paweenwich** [comment]
@daver78 @paagla123 We just found that your codeanywhere only support 1 SSH session.  So, what I propose to KD is not work.  However, like Dave suggest, it better if everyone has their own server and codeanywhere is free for single project.  We already experiment this idea by just setting Coa's codeanywhere.   We will set this env for everyone while you on the show.

**Comment by daver78** [comment]
@paweenwich Makes perfect sense; let me know how it goes with Coa's environment.  

Shall we close this Issue now?

**Comment by paagla123** [comment]
@daver78 @paweenwich I think we can close this now - right?
