### ISSUE TITLE
Google Tag manager cause javascript error

### ISSUE THREAD

**Issue by paweenwich** [coa0329/Bhaang#82]
@daver78 
For example, on editPromoteBlog.php

new error show up in console

"Unable to set property 'value' of undefined or null reference"

I think it case by these script in header.php

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-KWJ66T');</script>

I am not sure this is normal for google tag or not

**Comment by AumpaiFung** [comment]
About error:
![1504684465177](https://user-images.githubusercontent.com/30495097/30100949-c49fe0ac-9314-11e7-8d59-d1e38d77f824.jpg)

**Comment by paagla123** [comment]
@paweenwich @AumpaiFung is this issue fixed now?

**Comment by AumpaiFung** [comment]
@paagla123 
This is not fix.

**Comment by paweenwich** [comment]
Even simple page like this is fail 
`<!DOCTYPE html>
<html>
<head>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.js"></script> 

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KWJ66T');</script>

</head>
<body>
Test Google GTM
</body>
</html>`

The only way I can think of is that our key "GTM-KWJ66T" is fail.   Because the rest of the code just copy and paste from several GTM tutorial.

**Comment by daver78** [comment]
@paweenwich I think it is OK.  Do you see the same error on mindfireinc.com?

That said, I see the GA data correctly in their dashboard.  I think all is OK.

**Comment by paagla123** [comment]
Closed after discussion
