### ISSUE TITLE
[Audiences] Give UI some love

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#86]

**Comment by daver78** [comment]
First page OK for now:

![image](https://user-images.githubusercontent.com/7561473/30183464-65373ad2-93cf-11e7-999b-150d99df6645.png)

**Comment by daver78** [comment]
Add segment is OK now but should be re-tested by @paagla123:

![image](https://user-images.githubusercontent.com/7561473/30189064-c5c35d74-93e6-11e7-8fd8-32245e6036d5.png)

**Comment by daver78** [comment]
@coa0329 Few things needed here:

- Sometimes when I hit Save, it spins and spins.  Did I break something?  Other times it is fine.

- Can you apply the same look-and-feel to the `editContactAudience.html` view?

**Comment by coa0329** [comment]
Sometimes when I hit Save, it spins and spins. Did I break something? Other times it is fine. I ran out of time to troubleshoot but perhaps you can tell from your code.
- You may need this command $scope.$apply(); after $scope.state['Save'] = "Save";.

Can you apply the same look-and-feel to the editContactAudience.html view?
- Fixed

**Comment by daver78** [comment]
@coa0329 Thank you for applying to `editContactAudience.html`.

Did you add the `$scope.$apply(); after $scope.state['Save'] = "Save";`?   

@paagla123 Be advised of this open item during your testing.

**Comment by daver78** [comment]
@paagla123 Did you test the updates to `editContactAudience.html`? I don't think it pulls in your saved filter rows.

@coa0329 Can you double check this?  I think after you applied the updated look-and-feel, the saved rows do not populate.

**Comment by paagla123** [comment]
This problem occurs in Chrome and Edge - issue#103. I am going to close this one.
