### ISSUE TITLE
Summary of Misc. UI love 9/6/2017

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#90]
**welcome.php**
- Commented out “COPY” for now since it is not available.
- In campaign list, made entire row clickable with `ng-click` for easy and quick access, which included updating `header.php` with CSS: 
```
[ng-click] {
  cursor: pointer;
}
```
- Updated "Refer Friends" link to show coming soon message

**myCampaigns.php**
- Same changes as to `welcome.php`
- Added `<i class="fa fa-paper-plane-o" style="color:orange"></i>` to <h5> to match Home

**formLibrary.php**
- Changed "Last Modified" to "Modified" to match Home

**Comment by paagla123** [comment]
Closing now.
