### ISSUE TITLE
[Forms] {{item.fieldLists.length}} & {{item.allFieldName}}

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#91]
@AumpaiFung, Perhaps you're not done with this section, but I notice that:

-  `{{item.fieldLists.length}}` doesn't seem to always match with the # of fields (example below shows 3 fields when in fact there are 4); and

- `{{item.allFieldName}}` we would like this to display like "Field, Field, Field" (with a space after the coma)

![image](https://user-images.githubusercontent.com/7561473/30127129-fb4557ee-92f2-11e7-9311-f8dd800e0783.png)

**Comment by AumpaiFung** [comment]
@daver78  
I fixed it.

**Comment by daver78** [comment]
@AumpaiFung OK, I assume this only works for newly created forms and/or those that are edited post your fix?

Also, I notice that the field label for custom fields doesn't show up in the list.  Are you still working on this?

![image](https://user-images.githubusercontent.com/7561473/30171849-e5b3362a-93a7-11e7-825f-2f7551b72b15.png)

![image](https://user-images.githubusercontent.com/7561473/30171873-f7e58ad2-93a7-11e7-9fce-901e407fabe2.png)

**Comment by AumpaiFung** [comment]
I already fixed it.
The missing field name problem should not happen with the new create form.
For the old form I already fixed in davinci DB. 
Please try again.

**Comment by daver78** [comment]
@AumpaiFung thank you.  @paagla123 is this something you can verify, or do you want me to?

**Comment by paagla123** [comment]
This is fixed. Closing
