### ISSUE TITLE
[Promote a Blog Post] Give love to the "Plain Email" Template

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#92]

**Comment by daver78** [comment]
- Removed “View online” since I want this template to look handwritten
- Made a few small changes
- @paweenwich Can you please replace `PLAIN-EMAIL.html` with `PLAIN-EMAIL-D1.html`? 
- @paweenwich Can you also remove (or comment out) the other templates and just leave the updated PLAIN and COMPANY

**Comment by paweenwich** [comment]
Done. 
(Replace PLAN-EMAIL and COMPANY-EMAIL with D1 version and disable D# template from the list)

**Comment by daver78** [comment]
@paweenwich confirmed.  @paagla123 I'm closing this for now; any issues you find, please open a new Issue.
