### ISSUE TITLE
Make short PPT for Print 17 Team

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#94]
We need something visual to get everyone on the same page as to the DV value-prop, and how it fits into the MindFire ecosystem.  I'll do a short and concise PPT for everyone.

My intention is to lead with "what's the problem?" and then show the four parts of the MF planetary system, who each part is good for (and why), and basic pricing.

Should rock.

@Mcfarsheed Just adding you as FYI.

**Comment by Mcfarsheed** [comment]
Awesome! Let me know if you want me to look over when complete or if
there's anything I can do to help!

Sincerely,

Mackenzi
MindFireInc.
949-842-4388
www.mindfireinc.com

**Comment by daver78** [comment]
@Mcfarsheed You got it.  Thank you for including your contact information so I know how to reach you.

**Comment by paagla123** [comment]
@daver78 closing this now.

**Comment by daver78** [comment]
@paagla123 Thx good sire.
