### ISSUE TITLE
[Audiences] Apply UI love to importContact.php

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#95]

**Comment by daver78** [comment]
@paagla123 and @paweenwich Given that tomorrow I need to get back to "normal" work, I doubt I will be able to give love to those portion of the UI.  

@paagla123 what do you recommend?  We can tell the team not to go there, or caveat it and say it's a work in progress -- or maybe @coa0329 can give it love to match the rest of the UI as much as possible, and I can attend to it post P17?

![image](https://user-images.githubusercontent.com/7561473/30189501-21c09aea-93e9-11e7-95ae-0370b6538062.png)

**Comment by coa0329** [comment]
![116](https://user-images.githubusercontent.com/7914690/30204268-f9489614-94ae-11e7-9f70-06c73e4567d1.JPG)

I change the upload and import button to use the same UI as in promote blog.

**Comment by paagla123** [comment]
@daver78 @coa0329 what is teh status here - can we please close this now?

**Comment by daver78** [comment]
@paagla123 I'm going to assign it to me.  Coa gave it a 1st pass of love but there is more opportunity here I want to investigate.  I'll change assignment.

**Comment by paagla123** [comment]
@daver78 any updates here? Thx

**Comment by daver78** [comment]
@paagla123 I'm closing this one and moving to b-web repo.
