### ISSUE TITLE
[Website] Finalize so we are OK for now

### ISSUE THREAD

**Issue by daver78** [coa0329/Bhaang#99]
The website at [dv.mindfireinc.com](dv.mindfireinc.com) is good enough for now.  Needs a lot of work but if people don't read too carefully it should be OK.  There are some open items to button up.

**Comment by daver78** [comment]
@Mcfarsheed and @paagla123 here is what I did today:

- Made the FREE TRIAL form submit an email.  Will go to dg@mindfireinc.com and Kush (if he accepts Formspree).  
- We should tell our team if they want to sign people up for "early access" to use the contact form on the site and make a note of that in the comments
- I commented out the testis until we have
- I updated the value prop bullets

**Comment by paagla123** [comment]
@daver78 what's this Formspree?

**Comment by paagla123** [comment]
@daver78  - what about the add as seed form?
Also - what is testis?

**Comment by daver78** [comment]
@paagla123 See [https://formspree.io/](https://formspree.io/)

**Comment by daver78** [comment]
@paagla123 What do you mean about "Add as Seed Form"?  Am I forgetting about something?

Testis = testimonials

**Comment by paagla123** [comment]
@daver78  can we close this one now?

**Comment by daver78** [comment]
@paagla123 Yes -- except did you clarify what you mean about "Add as Seed Form"?  Did I fix that?

If not please create another Issue for me so I can fix.
